### ISSUE TITLE
How add more fields in registration form?

### ISSUE THREAD

**Issue by halk2269** [amnah/yii2-user#100]
1. I created a field in a database
2. I added 2 field to the form
<?= $form->field($user, 'first_name')->label(false)->textInput(array('placeholder' => 'First Name')) ?>
<?= $form->field($user, 'last_name')->label(false)->textInput(array('placeholder' => 'Last Name')) ?>
3. And amended ...\vendor\amnah\yii2-user\models\User.php
...
    public $first_name;
    public $last_name;
...
    public function rules()
    {
        $rules = [
...
            ['first_name', 'required'],
            ['last_name', 'required'],
...]

WHY this field not pass in the database???
![joxi_screenshot_1434489108393](https://cloud.githubusercontent.com/assets/11560804/8194651/a8806d3e-1485-11e5-9667-631dd711f470.png)

...ty...

**Comment by amnah** [comment]
Hmmm... Try removing  ```public $first_name; public $last_name; ``` from the model file.

**Comment by halk2269** [comment]
wow...workin. TY. 
I do not understand?....
Why not declare a variable?

**Comment by amnah** [comment]
It's how Yii2 models work - it uses the magic __get() and __set() methods to access the db columns. If you declare an attribute explicitly, it will use that instead (and thus not update the db).

http://www.yiiframework.com/doc-2.0/guide-db-active-record.html

*Note: The Active Record attributes are named after the associated table columns in a case-sensitive manner. Yii automatically defines an attribute in Active Record for every column of the associated table. You should NOT redeclare any of the attributes.*

**Comment by halk2269** [comment]
thanks for the answer.
