### ISSUE TITLE
Missing username on the registration page

### ISSUE THREAD

**Issue by DuskoV** [amnah/yii2-user#101]
Registration page doesn't have username box. How is username feature defined (user can't choose username at the time of registration)?

**Comment by amnah** [comment]
This isn't a bug - I decided on this for several reasons:

1) Less fields on registration = faster + easier to register
2) Many sites use email as the username
3) You'll probably [extend/override the view files](https://github.com/amnah/yii2-user#how-do-i-extend-this-package) anyway

But the quick way to do this is to simply enable the ```$requireUsername``` [property](https://github.com/amnah/yii2-user/blob/master/PROPERTIES.md)
