### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by macklus** [amnah/yii2-user#103]
From a fresh install of yii2-user, and after use neo/neo data to login, i get:

Undefined function $identity->updateLoginMeta();

Only way i can solve that is go to \amnah\yii2\user\models\User, on afterLogin function, and comment line:
$identity->updateLoginMeta();

**Comment by amnah** [comment]
Did you see the user component properly?

```php
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],
```

**Comment by amnah** [comment]
What version do you have installed? What's your config?

**Comment by arshadshaikh** [comment]
I've installed it but unable to login. Even with new user registered and confirmed but no good luck. Any idea? Any body can help me in that regard?

**Comment by mnglkhn** [comment]
hi, you need to actually confirm the email that would be sent at registration time. If your setup does not have email transmission configured then you need to confirm your email directly in the database.

**Comment by arshadshaikh** [comment]
I've done it @mnglkhn. Now, i m sure, there is something wrong that it does not let me login, bcos i don't get any error.

**Comment by amnah** [comment]
what's ur config? u didn't set it up properly

**Comment by arshadshaikh** [comment]
I've installed it locally on wamp on windows 7. I have 'PHP Version 5.5.12'.

**Comment by amnah** [comment]
no, I mean your yii2 config. the stuff in web.php ... did u follow the
installation instructions?

**Comment by arshadshaikh** [comment]
i've followed all the instruction. Registration form works very well and after that i've confirmed the user. Let me tell you i've put "amnah/yii2-user": "~3.0" in composer.json and then run the command composer update. In short from your url: https://github.com/amnah/yii2-user i 've followed till migration.

**Comment by amnah** [comment]
What error do you get?

**Comment by amnah** [comment]
What error do you get? What are the contents of your web.php config file?

**Comment by arshadshaikh** [comment]
<?php
return [
    'vendorPath' => dirname(dirname(__DIR__)) . '/vendor',
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => true,
            'messageConfig' => [
                'from' => ['admin@website.com' => 'Admin'], // this is needed for sending emails
                'charset' => 'UTF-8',
            ]
        ],
    ],
    'modules'    => [
        'user' => [
            'class' => 'amnah\yii2\user\Module',
        ],
    ],
];

**Comment by amnah** [comment]
Are you sure you're using the correct login page? ```/user/login```, not the default ```/site/login```

**Comment by arshadshaikh** [comment]
100% sure. I've updated menu too. Even checked again.

**Comment by amnah** [comment]
Then honestly I'm not sure ... everything looks good from what you've posted. 

At this point you'll have to trace the code and see what's happening. I would start [here](https://github.com/amnah/yii2-user/blob/master/models/forms/LoginForm.php#L164)

**Comment by arshadshaikh** [comment]
Yes. I've already checked it. It goes inside if block. And it also returns true, but i don't know whats wrong and then nothing happens. And it comes back login page without any error.

**Comment by amnah** [comment]
Hmmm that sounds like a server/environment issue then. Because if it's [returning true](http://www.yiiframework.com/doc-2.0/yii-web-user.html#login%28%29-detail), then you should be logged in.

Can you try using another module and see if it happens? [This](https://github.com/dektrium/yii2-user) is a good one

**Comment by amnah** [comment]
Hmmm one last thing to try: clear your cookies or use a private/incognito tab

**Comment by arshadshaikh** [comment]
I've tried with private/incognito tab, but no good luck. Let me try another module suggested by you.

I appreciate your support. Awesome.

Thank you so much
