### ISSUE TITLE
Please add a tag for version 3

### ISSUE THREAD

**Issue by sheershoff** [amnah/yii2-user#105]
For correct versioning on packagist and in composer.json please add correct git tag. I'd like to stick to the new major version 3, according to semver, to be sure it won't update itself to a backwards incompatible version 4 when it will be released and won't break the project. Thank you!

**Comment by amnah** [comment]
Sorry for the delay, wanted to fix up a few things first before releasing.

https://github.com/amnah/yii2-user/releases/tag/3.0.0
