### ISSUE TITLE
Google+ registration requires user to enter email

### ISSUE THREAD

**Issue by rawevolution** [amnah/yii2-user#106]
Hi there, Facebook registration is behaving perfectly and Twitter doesn't provide email in the response but Google+ registration requires the user to enter their email even though it's included in the response. Are you able to amend this please? Great plugin by the way!

**Comment by amnah** [comment]
I'm not sure what you mean, could you please provide more details? I just set it up for testing, and it's working fine for me; I don't need to enter any info, just accept the permissions.

**Comment by amnah** [comment]
Added to demo: http://yii2.amnahdev.com/user/login

**Comment by rawevolution** [comment]
Apologies Amnah, this was meant to be for dektrium's user plugin but I accidentally ended up on yours.

Cheers
