### ISSUE TITLE
RBAC component of the module

### ISSUE THREAD

**Issue by xiandalisay** [amnah/yii2-user#109]
It seems that the module is not extensible to the yii2 rbac migration. Wouldn't it be better if the roles are compliant to the migration since the children and rules can be configured on these tables?

**Comment by amnah** [comment]
I'm not sure what you mean? They're separate but can still work together, as the table names are different. Just follow the guide to set it up and use it:

http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#role-based-access-control-rbac
