### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by SickSight** [amnah/yii2-user#11]
Hey!

Is it planned the plugin to translate into other languages​​? I can offer for German, when the preparations are made.

**Comment by cesao** [comment]
Hey guy here is the protuguese (pt_BR - Brazil) translate!
    // models
   'ID' => 'Código',
    'User ID' => 'Código de Usuário',
    'Create Time' => 'Data de Criação',
    'Update Time' => 'Data de Atualização',
    'Full Name' => 'Nome completo',

    'Name' => 'Nome',
    'Can Admin' => 'Pode Administrar',

    'Role' => 'Papel',
    'Role ID' => 'Código do papel',
    'Status' => 'Estado',
    'Email' => 'E-mail',
    'New Email' => 'Novo E-mail',
    'Username' => 'Nome de Usuário',
    'Password' => 'Senha',
    'Auth Key' => 'Chave de Autorização',
    'Api Key' => 'Chave da API',
    'Login Ip' => 'IP de Conexão',
    'Login Time' => 'Data de Conexão',
    'Create Ip' => 'IP de Criação',
    'Ban Time' => 'Tempo de Suspensão',
    'Ban Reason' => 'Razão de Suspensão',
    'Current Password' => 'Senha Atual',
    'New Password' => 'Nova Senha',
    'Email Confirmation' => 'E-mail de Confirmação',

    'Provider' => 'Provedor',
    'Provider ID' => 'Código de provedor',
    'Provider Attributes' => 'Atributos de provedor',

    'Type' => 'Tipo',
    'Key' => 'Chave',
    'Consume Time' => 'Data de Consumo',
    'Expire Time' => 'Data de Expiração',

    // models/forms
    'Email not found' => 'E-mail não encontrado',
    'Email/username not found' => 'E-mail/Nome de utilizador não encontrado',
    'Username not found' => 'Nome de usuário não encontrado',
    'User is banned - {banReason}' => 'Usuário está banido - {banReason}',
    'Incorrect password' => 'Senha Incorreta',
    'Remember Me' => 'Lembrar-me',
    'Email is already active' => 'E-mail já em uso',

    // controllers
    'Successfully registered [ {displayName} ]' => 'Registado com sucesso [ {displayName} ]',
    ' - Please check your email to confirm your account' => ' - Por favor verifique o seu e-mail para confirmar a sua conta',
    'Account updated' => 'Conta atualizada',
    'Profile updated' => 'Perfil atualizado',
    'Confirmation email resent' => 'E-mail de confirmação reenviado',
    'Email change cancelled' => 'Mudança de e-mailo cancelada',
    'Instructions to reset your password have been sent' => 'Instruções para recuperar a sua senha foram enviadas',

    // mail
    'Please confirm your email address by clicking the link below:' => 'Por favor confirme o seu e-mail ao carregar no endereço abaixo:',
    'Please use this link to reset your password:' => 'Por favor utilize este enderenço para recuperar a sua senha:',

    // admin views
    'Users' => 'Utilizadores',
    'Banned' => 'Banido',
    'Create' => 'Criar',
    'Update' => 'Atualizar',
    'Delete' => 'Eliminar',
    'Search' => 'Procura',
    'Reset' => 'Reiniciar',
    'Create {modelClass}' => 'Criar {modelClass}',
    'Update {modelClass}: ' => 'Atualizar {modelClass}: ',
    'Are you sure you want to delete this item?' => 'Tem a certeza que pretende excluir este elemento?',

    // default views
    'Account' => 'Conta',
    'Pending email confirmation: [ {newEmail} ]' => 'Esperando confirmação do e-mail: [ {newEmail} ]',
    'Cancel' => 'Cancel',
    'Changing your email requires email confirmation' => 'Alterar o seu e-mail requer confirmação',
    'Confirmed' => 'Confirmado',
    'Error' => 'Erro',
    'Your email [ {email} ] has been confirmed' => 'O seu e-mail [ {email} ] foi confirmado',
    'Go to my account' => 'Ir para a minha conta',
    'Go home' => 'Ir para página inicial',
    'Log in here' => 'Entre aqui',
    'Invalid key' => 'Chave inválida',
    'Forgot password' => 'Senha esquecida',
    'Submit' => 'Enviar',
    'Yii 2 User' => 'Usuário de Yii 2',
    'Login' => 'Entrar',
    'Register' => 'Registrar-se',
    'Logout' => 'Sair',
    'Resend confirmation email' => 'Reenviar ce-mail de confirmação',
    'Profile' => 'Perfil',
    'Please fill out the following fields to login:' => 'Por favor preencha os campos seguintes para entrar:',
    'Please fill out the following fields to register:' => 'Por favor preencha os campos seguintes para se registar:',
    'Resend' => 'Reenviar',
    'Password has been reset' => 'Senha reiniciada',

**Comment by cesao** [comment]
Hey guy here is the portuese translate (pt_BR - Brazil)
    // models
    'ID' => 'Código',
    'User ID' => 'Código de Usuário',
    'Create Time' => 'Data de Criação',
    'Update Time' => 'Data de Atualização',
    'Full Name' => 'Nome completo',

    'Name' => 'Nome',
    'Can Admin' => 'Pode Administrar',

    'Role' => 'Papel',
    'Role ID' => 'Código do papel',
    'Status' => 'Estado',
    'Email' => 'E-mail',
    'New Email' => 'Novo E-mail',
    'Username' => 'Nome de Usuário',
    'Password' => 'Senha',
    'Auth Key' => 'Chave de Autorização',
    'Api Key' => 'Chave da API',
    'Login Ip' => 'IP de Conexão',
    'Login Time' => 'Data de Conexão',
    'Create Ip' => 'IP de Criação',
    'Ban Time' => 'Tempo de Suspensão',
    'Ban Reason' => 'Razão de Suspensão',
    'Current Password' => 'Senha Atual',
    'New Password' => 'Nova Senha',
    'Email Confirmation' => 'E-mail de Confirmação',

    'Provider' => 'Provedor',
    'Provider ID' => 'Código de provedor',
    'Provider Attributes' => 'Atributos de provedor',

    'Type' => 'Tipo',
    'Key' => 'Chave',
    'Consume Time' => 'Data de Consumo',
    'Expire Time' => 'Data de Expiração',

    // models/forms
    'Email not found' => 'E-mail não encontrado',
    'Email/username not found' => 'E-mail/Nome de utilizador não encontrado',
    'Username not found' => 'Nome de usuário não encontrado',
    'User is banned - {banReason}' => 'Usuário está banido - {banReason}',
    'Incorrect password' => 'Senha Incorreta',
    'Remember Me' => 'Lembrar-me',
    'Email is already active' => 'E-mail já em uso',

    // controllers
    'Successfully registered [ {displayName} ]' => 'Registado com sucesso [ {displayName} ]',
    ' - Please check your email to confirm your account' => ' - Por favor verifique o seu e-mail para confirmar a sua conta',
    'Account updated' => 'Conta atualizada',
    'Profile updated' => 'Perfil atualizado',
    'Confirmation email resent' => 'E-mail de confirmação reenviado',
    'Email change cancelled' => 'Mudança de e-mailo cancelada',
    'Instructions to reset your password have been sent' => 'Instruções para recuperar a sua senha foram enviadas',

    // mail
    'Please confirm your email address by clicking the link below:' => 'Por favor confirme o seu e-mail ao carregar no endereço abaixo:',
    'Please use this link to reset your password:' => 'Por favor utilize este enderenço para recuperar a sua senha:',

    // admin views
    'Users' => 'Utilizadores',
    'Banned' => 'Banido',
    'Create' => 'Criar',
    'Update' => 'Atualizar',
    'Delete' => 'Eliminar',
    'Search' => 'Procura',
    'Reset' => 'Reiniciar',
    'Create {modelClass}' => 'Criar {modelClass}',
    'Update {modelClass}: ' => 'Atualizar {modelClass}: ',
    'Are you sure you want to delete this item?' => 'Tem a certeza que pretende excluir este elemento?',

    // default views
    'Account' => 'Conta',
    'Pending email confirmation: [ {newEmail} ]' => 'Esperando confirmação do e-mail: [ {newEmail} ]',
    'Cancel' => 'Cancel',
    'Changing your email requires email confirmation' => 'Alterar o seu e-mail requer confirmação',
    'Confirmed' => 'Confirmado',
    'Error' => 'Erro',
    'Your email [ {email} ] has been confirmed' => 'O seu e-mail [ {email} ] foi confirmado',
    'Go to my account' => 'Ir para a minha conta',
    'Go home' => 'Ir para página inicial',
    'Log in here' => 'Entre aqui',
    'Invalid key' => 'Chave inválida',
    'Forgot password' => 'Senha esquecida',
    'Submit' => 'Enviar',
    'Yii 2 User' => 'Usuário de Yii 2',
    'Login' => 'Entrar',
    'Register' => 'Registrar-se',
    'Logout' => 'Sair',
    'Resend confirmation email' => 'Reenviar ce-mail de confirmação',
    'Profile' => 'Perfil',
    'Please fill out the following fields to login:' => 'Por favor preencha os campos seguintes para entrar:',
    'Please fill out the following fields to register:' => 'Por favor preencha os campos seguintes para se registar:',
    'Resend' => 'Reenviar',
    'Password has been reset' => 'Senha reiniciada',

**Comment by cesao** [comment]
Hey guy here is the portuese translate (pt_BR - Brazil)

'ID' => 'Código',
    'User ID' => 'Código de Usuário',
    'Create Time' => 'Data de Criação',
    'Update Time' => 'Data de Atualização',
    'Full Name' => 'Nome completo',

    'Name' => 'Nome',
    'Can Admin' => 'Pode Administrar',

    'Role' => 'Papel',
    'Role ID' => 'Código do papel',
    'Status' => 'Estado',
    'Email' => 'E-mail',
    'New Email' => 'Novo E-mail',
    'Username' => 'Nome de Usuário',
    'Password' => 'Senha',
    'Auth Key' => 'Chave de Autorização',
    'Api Key' => 'Chave da API',
    'Login Ip' => 'IP de Conexão',
    'Login Time' => 'Data de Conexão',
    'Create Ip' => 'IP de Criação',
    'Ban Time' => 'Tempo de Suspensão',
    'Ban Reason' => 'Razão de Suspensão',
    'Current Password' => 'Senha Atual',
    'New Password' => 'Nova Senha',
    'Email Confirmation' => 'E-mail de Confirmação',

    'Provider' => 'Provedor',
    'Provider ID' => 'Código de provedor',
    'Provider Attributes' => 'Atributos de provedor',

    'Type' => 'Tipo',
    'Key' => 'Chave',
    'Consume Time' => 'Data de Consumo',
    'Expire Time' => 'Data de Expiração',

    // models/forms
    'Email not found' => 'E-mail não encontrado',
    'Email/username not found' => 'E-mail/Nome de utilizador não encontrado',
    'Username not found' => 'Nome de usuário não encontrado',
    'User is banned - {banReason}' => 'Usuário está banido - {banReason}',
    'Incorrect password' => 'Senha Incorreta',
    'Remember Me' => 'Lembrar-me',
    'Email is already active' => 'E-mail já em uso',

    // controllers
    'Successfully registered [ {displayName} ]' => 'Registado com sucesso [ {displayName} ]',
    ' - Please check your email to confirm your account' => ' - Por favor verifique o seu e-mail para confirmar a sua conta',
    'Account updated' => 'Conta atualizada',
    'Profile updated' => 'Perfil atualizado',
    'Confirmation email resent' => 'E-mail de confirmação reenviado',
    'Email change cancelled' => 'Mudança de e-mailo cancelada',
    'Instructions to reset your password have been sent' => 'Instruções para recuperar a sua senha foram enviadas',

    // mail
    'Please confirm your email address by clicking the link below:' => 'Por favor confirme o seu e-mail ao carregar no endereço abaixo:',
    'Please use this link to reset your password:' => 'Por favor utilize este enderenço para recuperar a sua senha:',

    // admin views
    'Users' => 'Usuários',
    'Banned' => 'Banido',
    'Create' => 'Cadastrar',
    'Update' => 'Atualizar',
    'Delete' => 'Eliminar',
    'Search' => 'Procurar',
    'Reset' => 'Recuperar',
    'Create {modelClass}' => 'Criar {modelClass}',
    'Update {modelClass}: ' => 'Atualizar {modelClass}: ',
    'Are you sure you want to delete this item?' => 'Tem a certeza que pretende excluir este elemento?',

    // default views
    'Account' => 'Conta',
    'Pending email confirmation: [ {newEmail} ]' => 'Esperando confirmação do e-mail: [ {newEmail} ]',
    'Cancel' => 'Cancel',
    'Changing your email requires email confirmation' => 'Alterar o seu e-mail requer confirmação',
    'Confirmed' => 'Confirmado',
    'Error' => 'Erro',
    'Your email [ {email} ] has been confirmed' => 'O seu e-mail [ {email} ] foi confirmado',
    'Go to my account' => 'Ir para a minha conta',
    'Go home' => 'Ir para página inicial',
    'Log in here' => 'Entre aqui',
    'Invalid key' => 'Chave inválida',
    'Forgot password' => 'Senha esquecida',
    'Submit' => 'Enviar',
    'Yii 2 User' => 'Usuário de Yii 2',
    'Login' => 'Entrar',
    'Register' => 'Registrar-se',
    'Logout' => 'Sair',
    'Resend confirmation email' => 'Reenviar ce-mail de confirmação',
    'Profile' => 'Perfil',
    'Please fill out the following fields to login:' => 'Por favor preencha os campos seguintes para entrar:',
    'Please fill out the following fields to register:' => 'Por favor preencha os campos seguintes para se registar:',
    'Resend' => 'Reenviar',
    'Password has been reset' => 'Senha reiniciada',

**Comment by amnah** [comment]
Please send pull requests for further translations
