### ISSUE TITLE
Error on register user 

### ISSUE THREAD

**Issue by gugoan** [amnah/yii2-user#110]
Hi,
The following error occurs when a User attempts to create an account, the address **/index.php?r=user/register**.

I think it started to happen after the last update by composer
```
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: amnah\yii2\user\models\UserKey::key_value

 in /home/path/myapp/vendor/yiisoft/yii2/base/Component.php
```
```
                    $behavior->$name = $value;
 
                    return;
                }
            }
        }
        if (method_exists($this, 'get' . $name)) {
            throw new InvalidCallException('Setting read-only property: ' . get_class($this) . '::' . $name);
        } else {
            throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);
        }
    }
 
    /**
     * Checks if a property is set, i.e. defined and not null.
     * This method will check in the following order and act accordingly:
     *
     *  - a property defined by a setter: return whether the property is set
     *  - a property of a behavior: return whether the property is set
        // set/update data
        $model->user_id     = $userId;
        $model->type        = $type;
        $model->create_time = date("Y-m-d H:i:s");
        $model->expire_time = $expireTime;
        $model->key_value   = Yii::$app->security->generateRandomString();
        $model->save(false);
        return $model;
    }
 
    /**
     * Find an active userKey by userId
```

**Comment by amnah** [comment]
did you install the package a while back and then recently update? looks
like you need to change the db column user_key.key to user_key.key_value

**Comment by gugoan** [comment]
yes, i install de packege a while back...
I try rename the db column, but error persists.. There is another change?

**Comment by amnah** [comment]
that should do it... it's a simple set value based on column name. unless
you did something drastic which I have no idea about

if possible can you just uninstall and reinstall the package? (with
migration and everything) otherwise you'll need to go through the code
manually ...

**Comment by gugoan** [comment]
Thank Amnah
I reinstalled the system startup and compared with the current. Really enough to change the column name. Everything worked!
I do not know why it did not work before
