### ISSUE TITLE
Send mail just in plain text

### ISSUE THREAD

**Issue by gugoan** [amnah/yii2-user#111]
Hello,

I am using its extension and e-mailing is working properly. However the send mail message is coming just as text (does not come as a html link). I did the tests and CONFIRM MAIL and FORGOT MAIL.

My MAILER component settings are as follows:
```
'mailer' => [
    'class' => 'yii\swiftmailer\Mailer',
    'useFileTransport' => false,
    'messageConfig' => [
        'from' => ['support@myprovider.org' => 'Support'], // this is needed for sending emails
        'charset' => 'UTF-8',
    ]
],
```

**Comment by amnah** [comment]
Hmmm, working fine for me. Can I see your email content?


Message-ID: <35e15f86eaabbec85aa9575a9716588d@yii2.amnahdev.com>
Date: Tue, 15 Sep 2015 09:49:12 +0000
Subject: amnah - yii2 - Forgot password
From: amnah <amnah@amnah.mailgun.org>
To: neo@neo.com
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="_=_swift_v4_1442310552_8ee21e5c1c904f3a1212ea75839386ac_=_"


--_=_swift_v4_1442310552_8ee21e5c1c904f3a1212ea75839386ac_=_
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

amnah - yii2 - Forgot password

Please use this link to reset your password:

http://yii2.amnahdev.com/user/reset?key=randomKey

--_=_swift_v4_1442310552_8ee21e5c1c904f3a1212ea75839386ac_=_
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.=
org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns=3D"http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DUTF=
-8" />
    <title></title>
    </head>
<body>

<h3>amnah - yii2 - Forgot password</h3>

<p>Please use this link to reset your password:</p>

<p>http://yii2.amnahdev.com/user/reset?key=randomKey</p>
</body>
</html>


--_=_swift_v4_1442310552_8ee21e5c1c904f3a1212ea75839386ac_=_--

**Comment by gugoan** [comment]
I made a new test with an earlier copy of the site and worked properly.
I had previously tested with Outlook and Gmail.

ok now
