### ISSUE TITLE
[Yii2-user] *** failed to apply m150214_044831_init_user (time: 0.003s)

### ISSUE THREAD

**Issue by nikhilgopalakrishna** [amnah/yii2-user#113]
Run migration file 
php yii migrate --migrationPath=@vendor/amnah/yii2-user/migrations

----failed

Log:
Yii Migration Tool (based on Yii v2.0.7-dev)

Total 1 new migration to be applied:
        m150214_044831_init_user

Apply the above migration? (yes|no) [no]:yes
*** applying m150214_044831_init_user
    > create table {{%role}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'role' already exists
The SQL being executed was: CREATE TABLE `role` (
        `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `name` varchar(255) not null,
        `create_time` timestamp null default null,
        `update_time` timestamp null default null,
        `can_admin` smallint(6) not null default 0
) CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB (/var/www/html/kw/vendor/yiisoft/yii2/db/Schema.php:628)
#0 /var/www/html/kw/vendor/yiisoft/yii2/db/Command.php(791): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `r...')
#1 /var/www/html/kw/vendor/yiisoft/yii2/db/Migration.php(260): yii\db\Command->execute()
#2 /var/www/html/kw/vendor/amnah/yii2-user/migrations/m150214_044831_init_user.php(24): yii\db\Migration->createTable('{{%role}}', Array, 'CHARACTER SET u...')
#3 /var/www/html/kw/vendor/yiisoft/yii2/db/Migration.php(93): m150214_044831_init_user->safeUp()
#4 /var/www/html/kw/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(492): yii\db\Migration->up()
#5 /var/www/html/kw/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(129): yii\console\controllers\BaseMigrateController->migrateUp('m150214_044831_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 /var/www/html/kw/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /var/www/html/kw/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/html/kw/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#10 /var/www/html/kw/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#11 /var/www/html/kw/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('migrate', Array)
#12 /var/www/html/kw/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('migrate', Array)
#13 /var/www/html/kw/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /var/www/html/kw/yii(27): yii\base\Application->run()
#15 {main}
*** failed to apply m150214_044831_init_user (time: 0.003s)

Migration failed. The rest of the migrations are canceled.

**Comment by amnah** [comment]
looks like you a already have a role table for some reason

 create table {{%role}} ...Exception: SQLSTATE[42S01]: Base table or view
already exists: 1050 Table 'role' already exists

**Comment by nikhilgopalakrishna** [comment]
Hello,

 1) The migration problem is fixed after I delete role table and run migration again.
 But now I unable to login with neo/neo - Invalid username and password 
 when I checked for user neo is DB it is present.

2) Unable to signup : 
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: common\models\User::password_hash

log:

1. in /vendor/yiisoft/yii2/base/Component.php at line 197
188189190191192193194195196197198199200201202203204205206                    $behavior->$name = $value;
 
                    return;
                }
            }
        }
        if (method_exists($this, 'get' . $name)) {
            throw new InvalidCallException('Setting read-only property: ' . get_class($this) . '::' . $name);
        } else {
            throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);
        }
    }
 
    /**
     * Checks if a property is set, i.e. defined and not null.
     * This method will check in the following order and act accordingly:
     *
     *  - a property defined by a setter: return whether the property is set
     *  - a property of a behavior: return whether the property is set

2. in /vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 267 – yii\base\Component::__set('password_hash', '$2y$13$E2VshrSKVbFHa9MRlMY.n.TUm...')
3. in /common/models/User.php at line 162 – yii\db\BaseActiveRecord::__set('password_hash', '$2y$13$E2VshrSKVbFHa9MRlMY.n.TUm...')
156157158159160161162163164165166167168     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }
 
    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
4. in /frontend/models/SignupForm.php at line 50 – common\models\User::setPassword('user1test')
44454647484950515253545556    public function signup()
    {
        if ($this->validate()) {
            $user = new User();
            $user->username = $this->username;
            $user->email = $this->email;
            $user->setPassword($this->password);
            $user->generateAuthKey();
            if ($user->save()) {
                return $user;
            }
        }
 
5. in /frontend/controllers/SiteController.php at line 153 – frontend\models\SignupForm::signup()
147148149150151152153154155156157158159     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }
 
6. frontend\controllers\SiteController::actionSignup()
7. in /vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([frontend\controllers\SiteController, 'actionSignup'], [])
8. in /vendor/yiisoft/yii2/base/Controller.php at line 151 – yii\base\InlineAction::runWithParams(['r' => 'site/signup'])
9. in /vendor/yiisoft/yii2/base/Module.php at line 455 – yii\base\Controller::runAction('signup', ['r' => 'site/signup'])
10. in /vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('site/signup', ['r' => 'site/signup'])
11. in /vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(yii\web\Request)
12. in /frontend/web/index.php at line 18 – yii\base\Application::run()
12131415161718    require(__DIR__ . '/../../common/config/main-local.php'),
    require(__DIR__ . '/../config/main.php'),
    require(__DIR__ . '/../config/main-local.php')
);
 
$application = new yii\web\Application($config);
$application->run();
 $_GET = [
    'r' => 'site/signup',
];

$_POST = [
    '_csrf' => 'V29SVFNqUU09BjMfFgYFew0bYzA5JDUAOBUQYGAsCw9mAStlFy85Bw==',
    'SignupForm' => [
        'username' => 'user1',
        'email' => 'user1@test.com',
        'password' => 'user1test',
    ],
    'signup-button' => '',
];

Thanks.

**Comment by amnah** [comment]
I don't know what that is - that's not my code, and I don't recognize any of it. 

Are you sure you're in the right github repo? Looks like a completely different user module

**Comment by nikhilgopalakrishna** [comment]
Hello,

 I installed Yii2-user again using  composer "amnah/yii2-user": "~3.0"

1) Login : neo/neo is not working.

2) Error on Sigup:
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: common\models\User::password_hash

1. in /var/www/html/kw/vendor/yiisoft/yii2/base/Component.php at line 197
188189190191192193194195196197198199200201202203204205206                    $behavior->$name = $value;
 
                    return;
                }
            }
        }
        if (method_exists($this, 'get' . $name)) {
            throw new InvalidCallException('Setting read-only property: ' . get_class($this) . '::' . $name);
        } else {
            throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);
        }
    }
 
    /**
     * Checks if a property is set, i.e. defined and not null.
     * This method will check in the following order and act accordingly:
     *
     *  - a property defined by a setter: return whether the property is set
     *  - a property of a behavior: return whether the property is set
2. in /var/www/html/kw/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 267 – yii\base\Component::__set('password_hash', '$2y$13$MP67VMgmUNgs55ARcevlOuHzY...')
3. in /var/www/html/kw/common/models/User.php at line 162 – yii\db\BaseActiveRecord::__set('password_hash', '$2y$13$MP67VMgmUNgs55ARcevlOuHzY...')
156157158159160161162163164165166167168     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }
 
    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
4. in /var/www/html/kw/frontend/models/SignupForm.php at line 50 – common\models\User::setPassword('user1password')
44454647484950515253545556    public function signup()
    {
        if ($this->validate()) {
            $user = new User();
            $user->username = $this->username;
            $user->email = $this->email;
            $user->setPassword($this->password);
            $user->generateAuthKey();
            if ($user->save()) {
                return $user;
            }
        }
 
5. in /var/www/html/kw/frontend/controllers/SiteController.php at line 153 – frontend\models\SignupForm::signup()
147148149150151152153154155156157158159     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }
 
6. frontend\controllers\SiteController::actionSignup()
7. in /var/www/html/kw/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([frontend\controllers\SiteController, 'actionSignup'], [])
8. in /var/www/html/kw/vendor/yiisoft/yii2/base/Controller.php at line 151 – yii\base\InlineAction::runWithParams(['r' => 'site/signup'])
9. in /var/www/html/kw/vendor/yiisoft/yii2/base/Module.php at line 455 – yii\base\Controller::runAction('signup', ['r' => 'site/signup'])
10. in /var/www/html/kw/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('site/signup', ['r' => 'site/signup'])
11. in /var/www/html/kw/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(yii\web\Request)
12. in /var/www/html/kw/frontend/web/index.php at line 18 – yii\base\Application::run()
12131415161718    require(__DIR__ . '/../../common/config/main-local.php'),
    require(__DIR__ . '/../config/main.php'),
    require(__DIR__ . '/../config/main-local.php')
);
 
$application = new yii\web\Application($config);
$application->run();
 $_GET = [
    'r' => 'site/signup',
];

$_POST = [
    '_csrf' => 'cW5kX19abFk3FElmDg4oG0RaUgtmPyUOFCcuZxYMVQhIDzsoBy0oDQ==',
    'SignupForm' => [
        'username' => 'user1',
        'email' => 'user1@test.com',
        'password' => 'user1password',
    ],
    'signup-button' => '',
];

Thanks.

**Comment by nikhilgopalakrishna** [comment]
Any possible solution??

**Comment by amnah** [comment]
Well this is a bit beyond the scope of this module. It looks like you're working in a custom file that's not part of this module ```common\models\User```

The error is caused by your User model not having ```password_hash``` property. It needs to either exist in the database or have a class property, eg, ```public $password_hash;```
