### ISSUE TITLE
Set up on Facebook and Google+

### ISSUE THREAD

**Issue by gugoan** [amnah/yii2-user#114]
Hi,
What is the right way to set the parameters on Facebook and Google+ to use Social authentication?

**In Google+ is appearing:**
That’s an error.
Error: redirect_uri_mismatch

**In Facebook is appearing:**
The URL entered is not permitted by the application configuration: One or more of the provided URLs are not allowed in the application settings. The URL must match the URL of the website or URL Canvas, or domain should be a subdomain of one of the application domains

**Comment by gugoan** [comment]
In his DEMO worked so well, can show how it is configured the parameters ? In https://console.developers.google.com/project and https://developers.facebook.com

**Comment by amnah** [comment]
for google try this https://github.com/amnah/yii2-user/blob/master/SOCIAL.md#google

**Comment by amnah** [comment]
for facebook http://i.imgur.com/zi8kDOY.jpg

**Comment by gugoan** [comment]
For Facebook, I tried as in your example, but the parameter "Secure Canvas URL" is required. How did you do?

To "Advanced" is set up the tab?

**Comment by gugoan** [comment]
was a bug in GoogleOAuth client. 
fixed by ercling, by overriding getReturnUrl() method:
```
use yii\authclient\clients\GoogleOAuth as BaseGoogleOAuth;
class GoogleOAuth extends BaseGoogleOAuth{
    private $_returnUrl;

    /**
     * Fix double encoded redirect_uri
     *
     * @return string
     */
    public function getReturnUrl()
    {
        if ($this->_returnUrl === null) {
            $this->_returnUrl = $this->defaultReturnUrl();
        }
        return urldecode($this->_returnUrl);
    }
}
```
