### ISSUE TITLE
Login redirect / message does'nt work on production

### ISSUE THREAD

**Issue by DarkRide** [amnah/yii2-user#115]
Hi, 

Thanks for this plugin. 
I have some issues with it, first the message "you may login with neo/neo" should'nt be displayed on production environment ( YII_ENV = prod ) but the hardest issue is I can't login when YII_ENV <> dev.

User is not set in php session and redirection is not made, I loop on the login page (user/login) without any message.

Thanks for your help

**Comment by amnah** [comment]
are you using the advanced app? did you set the user component properly in
frontend/backend config? (not common config)

**Comment by DarkRide** [comment]
I'm using basic app, all my application work on development environment (so everything seems to be well configured I think :-( )
Problem is on production environment

**Comment by amnah** [comment]
Ummm sounds like either a config or server. I guess easiest to start with the config, what's different from your dev and prod environment?

**Comment by DarkRide** [comment]
I use docker container (apache + php7) for both , same config just an apache var environment set to "dev" to configure the YII_ENV constant in web/index.php

**Comment by amnah** [comment]
Umm I'm not really sure then :/  You might need to go through the code and print statements to see what's happening, it seems like it would be a session issue, maybe something wrong with file permissions?

**Comment by DarkRide** [comment]
Found something :)
Authentificated users can't acces /user/login page (403 error), development envirnment allow to view the error message when production environment automaticaly crash (and maybe don't register user in session)

**Comment by DarkRide** [comment]
This behavior is caused by $this->goBack() controller's method when previous page is already "/user/login"

**Comment by amnah** [comment]
Hmm ... what a weird bug. Not sure how it would store ```user/login``` as the returnUrl, and not sure why it wouldn't show the 403 error on production. 

For now, I've added a check to try and prevent this. Thanks!

**Comment by DarkRide** [comment]
For information, I've changed : 

public $loginRedirect = '/site/index';

in module.php on line 65 and problem is "solved"
