### ISSUE TITLE
Integrity constraint violation: 1048 Column 'user_id' cannot be null

### ISSUE THREAD

**Issue by umanamente** [amnah/yii2-user#119]
Tried to login a new user using a social network integration (VKontakte). It gave me this error:
```
Integrity constraint violation: 1048 Column 'user_id' cannot be null
The SQL being executed was: INSERT INTO `ww_profile` (`full_name`, `user_id`, `created_at`, `updated_at`) VALUES ('John Doe', NULL, '2015-12-13 13:16:20', '2015-12-13 13:16:20')
```
Using version **4.0.0**

**Comment by amnah** [comment]
Hmmm looks like it would be this line:

https://github.com/amnah/yii2-user/blob/master/controllers/AuthController.php#L197

Can you check to see what the $user is before? I don't currently have a vkontakte account to test this:

    $user->setRegisterAttributes($role::ROLE_USER, $user::STATUS_ACTIVE)->save();
    print_r($user); // <----- check what this is
    $profile->setUser($user->id)->save();

It looks like the $user is failing to save, so maybe check errors:

    print_r($user->errors);

What I imagine happened is that email is required, but the vkontakte account doesn't have one

https://github.com/amnah/yii2-user/blob/master/controllers/AuthController.php#L350

**Comment by umanamente** [comment]
$user->errors:
      [0] => Username can contain only letters, numbers, and "_"
Yeah, VKontakte account first_name and last_name contains non-ASCII letters (they are russian in UTF8 generally because VK.com is a russian network). One should use "username" or "id" attribute.

**Comment by amnah** [comment]
Thanks!
