### ISSUE TITLE
User table in one database, role/authentication checks from app primarily using different database

### ISSUE THREAD

**Issue by jlounds** [amnah/yii2-user#122]
I have a multi-app Yii2 setup that, from a user's perspective, is really just one web app. Is there a way to tell yii2-user which database to use? If not, is my best option to duplicate all of the user tables? (profile, role, user, etc)

E.g., app1 config:

'components' => [
        ...
        'db' => require(__DIR__ . '/db.php'),
        'db2' => require(__DIR__ . '/db2.php'),
]

app2 config:

'components' => [
        ...
        'db' => require(__DIR__ . '/db2.php'),
        'db2' => require(__DIR__ . '/db.php'),
]

Thank you!

Jeremy

**Comment by amnah** [comment]
Yes, there's an ActiveRecord function that can help with this:

```php
class Customer extends ActiveRecord
{
    public static function getDb()
    {
        // use the "db2" application component
        return \Yii::$app->db2;  
    }
}
```
http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#db-connection
