### ISSUE TITLE
Email rule unique only on default controller/views?

### ISSUE THREAD

**Issue by cicsolutions** [amnah/yii2-user#123]
Hello, and thank you so much for all you do.  I use the amnah user module at the base of all my Yii projects, and I have learned a ton from reviewing your code!

I'm wondering if you can help me understand an issue I'm seeing with ajax validation and the "unique" rule for the email field.  In the admin/create process, the ajax validation for the email field triggers when the field is blank or the email address is not valid, but the unique rule doesn't trigger until the form is submitted.

Conversely, in the default/register process, the ajax validation triggers if the email address is already registered.

I don't seem to understand how this his happening, given that the model rule is:
```
[['email', 'username'], 'unique'],
```
I see this rule and think that both fields should be unique in all scenarios.  But somehow that's not how it's working.  Email is triggering unique rule on submit, but then the ajax validation seems to trigger for unique only on the default/register and not the admin/create controllers & views.

I've researched a lot, and I've wondered if using a form validationUrl would help things, but I can't seem to crack this nut.  It makes sense that using a special condition to trap ajax is perhaps what's needed, and I see the following code that you are using in the default/register controller method that you are not using in the admin/create controller method, but I dont't quite understand how it's all working.
```
if (Yii::$app->request->isAjax) {
    Yii::$app->response->format = Response::FORMAT_JSON;
    return ActiveForm::validate($user, $profile);
}
```

Any ideas, questions, suggestions you may have are very much appreciated!

**Comment by amnah** [comment]
You're on the right track - the difference between the two is indeed the ajax validation in ```default/register```. Currently the ```admin/create function``` is using only javascript validation, not ajax.

In order to make this work, you'll need to do two things:

1) Enable ajax validation in the form

```php
// vendor/amnah/yii2-user/views/admin/_form.php
    <?php $form = ActiveForm::begin([
        'enableAjaxValidation' => true, // by default, only 'enableClientValidation' => true
    ]); ?>
```

2) Add ajax validation to the AdminController::actionCreate()

```php
// vendor/amnah/yii2-user/controllers/AdminController.php

// other use calls
use yii\web\Response;
use yii\widgets\ActiveForm;

class AdminController extends Controller
{
    /**
     * Create a new User model. If creation is successful, the browser will
     * be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        /** @var \amnah\yii2\user\models\User $user */
        /** @var \amnah\yii2\user\models\Profile $profile */

        $user = $this->module->model("User");
        $user->setScenario("admin");
        $profile = $this->module->model("Profile");

        $post = Yii::$app->request->post();
        $userLoaded = $user->load($post);
        $profile->load($post);

        // validate for ajax request
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($user, $profile);
        }

        if ($userLoaded && $user->validate() && $profile->validate()) {
            $user->save(false);
            $profile->setUser($user->id)->save(false);
            return $this->redirect(['view', 'id' => $user->id]);
        }

        // render
        return $this->render('create', compact('user', 'profile'));
    }
}
```

**Comment by cicsolutions** [comment]
Holy cow!  You are AWESOME!  This makes so much better sense to me now.  
```
Currently the admin/create function is using only javascript validation, not ajax.
```
Of course the 'unique' validation needs ajax, whereas the other rules are just using client-side javascript! ;)  Boom!  I can't believe I didn't make that connection in my mind, and it clears everything up!

Thank you, so very much :)
