### ISSUE TITLE
'emailConfirmation' => 'false',

### ISSUE THREAD

**Issue by Dunc80** [amnah/yii2-user#124]
When I change this setting it makes no difference. I want users to be able to sign up and login to my site straight away.

 /**
     * @var bool If true, users will have to confirm their email address after registering (= email activation)
     */
    public $emailConfirmation = true;

**Comment by amnah** [comment]
What do you mean makes no difference - what doesn't work exactly?

**Comment by amnah** [comment]
Just tried it on my dev machine and it's working fine. Gonna need more info from you.

**Comment by Dunc80** [comment]
Hi, thanks for looking at this.
I have the following code in my config file. When I set 'emailConfirmation' as 'false' it still won't let a newly registered user login until clicking on the confirmation link in the email. This is exactly the same behaviour as when it is set as 'true'. I understood that this setting was supposed to eliminate the need for confirming the email before logging in. 


 'modules' => [
        'user' => [
            'class' => 'amnah\yii2\user\Module',
                        // set custom module properties here ...
                        'requireUsername' => 'true',
                        //'loginEmail' => 'false',
                        'emailConfirmation' => 'false',
            
			 			'modelClasses'  => [
            				'ForgotForm' => 'app\models\MyForgotForm',
            				'LoginEmailForm' => 'app\models\MyLoginEmailForm', 
            				'User' => 'app\models\User',
            				
        				],
        			],
    			],

**Comment by amnah** [comment]
Yes, it's supposed to. Your config looks correct, so I'm not really sure what's going on.

What classes have you extended/functions did you override?

Just to make sure, did you set the user component properly?

```php
// config/web.php
    'components' => [
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],
    ]
```

**Comment by Dunc80** [comment]
Yes I have the user component set properly. The only functions I have overridden were to change the subject of emails sent. I have just commented out the lines in my config file so it doesn't use my version of those classes and I still have the problem. 
I am using this version -  "amnah/yii2-user": "~4.0"

**Comment by amnah** [comment]
Ok then I have no idea. You'll have to walk through the code and try to see what's happening, I can't do much but speculate from here as I cannot reproduce this.

The first part is setting the user attributes, which sets the ```$user->status``` (```User::setRegisterAttributes()```

https://github.com/amnah/yii2-user/blob/master/models/User.php#L345

Then it checks what that status is, and it sends an email if needed. ```DefaultController::afterRegister()``

https://github.com/amnah/yii2-user/blob/master/controllers/DefaultController.php#L252

Can you walk through/print_r and see what's happening?
