### ISSUE TITLE
Add  attribute to registration form

### ISSUE THREAD

**Issue by steflight** [amnah/yii2-user#129]
how to add attribute to registration form ?

**Comment by cicsolutions** [comment]
Most likely you want to add a custom profile field.  The fields in the User model are less likely to need customizing, so I'd recommend you add your field to your database, and then you can override the  Profile model class and include your new profile field.  You'd also probably want to override any module views that need to include your custom field, such as the `views/default/registration.php` view file.

So, in your module configuration settings, you can override the module views and the Profile model class like this ...

    'components' => [
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],
	    'view' => [
	        'theme' => [
	            'pathMap' => [
	                '@vendor/amnah/yii2-user/views' => 'path/to-your/views',
	            ],
	        ],
	    ],
    ],
    'modules' => [
	    'user' => [
	        'class' => 'amnah\yii2\user\Module',
	        // set custom module properties here ...
	        'modelClasses'  => [
	            'Profile' => 'common\models\Profile', // the path to your Profile class - this is just one example
				// ... you can override other models if you need to 
	        ],
	    ],
	],

Be sure to check out the readme, as it covers how to extend this module too.
https://github.com/amnah/yii2-user#how-do-i-extend-this-package

**Comment by steflight** [comment]
Thank. I will try
