### ISSUE TITLE
How do I access profile fields?

### ISSUE THREAD

**Issue by jas0995** [amnah/yii2-user#132]
Please let me know if there is a better place to get support then here at github!  Thanks!
-------------------------

I am trying to get information out of the profile table.

I have tried several things such as:

        // get user profile information
        $userid = Yii::$app->user->user_id;
        $username = Yii::$app->user->full_name;

I get error: Getting unknown property: amnah\yii2\user\components\User::user_id

and....

        // get user profile information
        $userid = Yii::$app->profile->user_id;
        $username = Yii::$app->profile->full_name;

I get Error:  Getting unknown property: yii\web\Application::profile

So I am clearly missing something.

Can I get an example of how to access profile properties?

**Comment by amnah** [comment]
You can access the user via ```Yii::$app->user->identity```

So to get the profile ```Yii::$app->user->identity->profile```

**Comment by jas0995** [comment]
Great!  Thanks!!
