### ISSUE TITLE
update email or username check if exists in admin

### ISSUE THREAD

**Issue by davidlopes** [amnah/yii2-user#134]
During update in admin, is missing a error message when username or email already exists.
to resolve it you must add:
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($user, $profile);
        }
in function actionUpdate, file AdminController.php.

Very good extension.
Thanks, 
David

**Comment by amnah** [comment]
Fixed, thanks!

**Comment by kamskanagi** [comment]
is it possible to show a customise error message to the user on the user interface that the user already exists.

need your help.
