### ISSUE TITLE
Disable registration

### ISSUE THREAD

**Issue by archagy** [amnah/yii2-user#136]
I'm not sure if there are way to disable registration via module like "enableRegistration => false".

**Comment by amnah** [comment]
Unfortunately there isn't. You'll need to [extend](https://github.com/amnah/yii2-user#how-do-i-extend-this-package) the [default controller](https://github.com/amnah/yii2-user/blob/master/controllers/DefaultController.php), something like this:

```php
public function actionRegister()
{
    return $this->redirect(["/user/login"]);
}
```

**Comment by archagy** [comment]
Thanks for the answer !
