### ISSUE TITLE
try to login via FB/Google on demo here is the issue

### ISSUE THREAD

**Issue by wiwigogit** [amnah/yii2-user#137]
Try to login via FB/Google on demo here is the issue:
![user module error1](https://cloud.githubusercontent.com/assets/17021948/13027435/3f7614d8-d276-11e5-8264-664426836e18.png)

After registration then I have got the following error:

![user module error2](https://cloud.githubusercontent.com/assets/17021948/13027440/627ac3f2-d276-11e5-81ce-2d2fdec94d88.png)

**Comment by amnah** [comment]
Ugh not again. This is a dns issue with my webhost :/

Looks like I'll need to switch hosts this weekend. Thanks for the heads up
