### ISSUE TITLE
On update form it submits when clicking on form

### ISSUE THREAD

**Issue by DiegoGallegos4** [amnah/yii2-user#138]
Hi,

Whenever i want to edit a user it submits itself. It happens on the following fashion:

1. Click on a field
2. Click on a second field --> it triggers submit

I already disabled all my javascript files and still does it. 

Any help on this?

**Comment by amnah** [comment]
Hmmm what exactly do you mean by submits itself? It should be making an ajax call to itself for validation

https://github.com/amnah/yii2-user/blob/master/controllers/AdminController.php#L133-L136

**Comment by DiegoGallegos4** [comment]
By submitting it self is that whenever I click a field for the second time, it submits the form without letting me continue editing it. As I commented above I disabled all my js files to discard that the error was on my side.

**Comment by amnah** [comment]
Woops, I forgot to create a tag/release for that latest commits :(

Try running ```composer update``` to get the latest version, and then let me know if that fixes it for you.
