### ISSUE TITLE
signup: unknown property: password_hash 

### ISSUE THREAD

**Issue by AlexanderSchmutz** [amnah/yii2-user#140]
- advanced template
- on user signup

Getting error:
unknown property: common\models\User::password_hash

config in common/config/main.php:
(user deleted in frontend/backend)
```php
return [
    'vendorPath' => dirname(dirname(__DIR__)) . '/vendor',
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],
    ],
    'modules' => [
        'user' => [
            'class' => 'amnah\yii2\user\Module',
        ],
    ],
];
```

**Comment by amnah** [comment]
Hmmm possibly one (or both) of these:

1) You're using the built-in [yii2-advanced-app signup functionality](https://github.com/yiisoft/yii2-app-advanced/blob/master/frontend/controllers/SiteController.php#L149-L163) when you should be using this [module's functionality](https://github.com/amnah/yii2-user/blob/master/controllers/DefaultController.php#L194-L241) instead. 

In other words, your url should be ```/user/register``` and not ```/site/signup```

2) You're using the built-in [yii2-advanced-app model](https://github.com/yiisoft/yii2-app-advanced/blob/master/common/models/User.php) which is a model class extending the generic ```yii\db\ActiveRecord```. You'll need to extend ```amnah\yii2\user\models\User``` instead

**Comment by AlexanderSchmutz** [comment]
Oh - ok, url /user/register works for me. Thanks
