### ISSUE TITLE
mailer not working

### ISSUE THREAD

**Issue by rd1571** [amnah/yii2-user#144]
Hi Amnah,

i have problem on sending email after register.. But i get this message after register "Successfully registered [ test-reply@gmail.com ] - Please check your email to confirm your account"

'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => true,
            'messageConfig' => [
                'from' => ['admin@website.com' => 'Admin'], // this is needed for sending emails
                'charset' => 'UTF-8',
            ],
            'transport' => [
                 'class' => 'Swift_SmtpTransport',
                 'host' => 'smtp.gmail.com',
                 'username' => 'test-reply@gmail.com',
                 'password' => 'test!reply123',
                 'port' => '587',
                 'encryption' => 'tls',
             ],
        ],

I also tried to change the port to '465' and the encryption to 'ssl'.. still no luck.. Please help!!

**Comment by amnah** [comment]
if you're trying to send real emails, you need to disable ```$useFileTransport```

http://www.yiiframework.com/doc-2.0/yii-mail-basemailer.html#$useFileTransport-detail

**Comment by rd1571** [comment]
I've changed the 'useFileTransport' => false, nothing happenned..

**Comment by amnah** [comment]
im not sure then. youll need to debug yourself

http://www.yiiframework.com/doc-2.0/guide-tutorial-mailing.html

do some print_r / echo commands to see what the email result is

https://github.com/amnah/yii2-user/blob/master/models/User.php#L474-L496

**Comment by amnah** [comment]
you may want to use a real, dedicated email service instead of gmail. would be more reliable

mailgun
sendgrid
mandrill
postmark
etc
