### ISSUE TITLE
composer "amnah/yii2-user": "^5.0" gives error

### ISSUE THREAD

**Issue by Marcuzzz** [amnah/yii2-user#145]
[Symfony\Component\Console\Exception\CommandNotFoundException]     
  There are no commands defined in the "amnah/yii2-user" namespace.

**Comment by amnah** [comment]
composer install

**Comment by Marcuzzz** [comment]
MarcBookPro:yii-application marcbookpro$ composer install "amnah/yii2-user": "^5.0"
Invalid argument amnah/yii2-user: ^5.0. Use "composer require amnah/yii2-user: ^5.0" instead to add packages to your composer.json.
MarcBookPro:yii-application marcbookpro$ composer require "amnah/yii2-user": "^5.0"

                                                                                                                                        
  [InvalidArgumentException]                                                                                                            
  Could not find package ^5.0 at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
                                                                                                                                        

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

**Comment by Marcuzzz** [comment]
composer.json changed to dev:
terminal: composer require "amnah/yii2-user": "^5.0"
 [InvalidArgumentException]                                                                                                         
 Could not find package ^5.0 at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

**Comment by amnah** [comment]
hmm what happens if you try taking out the number

just require amnah/yii2-user

**Comment by Marcuzzz** [comment]
That works thanks!
( - Installing amnah/yii2-user (5.0.2) Loading from cache )

**Comment by abhimanyunaikare** [comment]
Could not parse version constraint : Invalid version string

**Comment by abhimanyunaikare** [comment]
in terminal composer require "amnah/yii2-user"

**Comment by amnah** [comment]
@abhimanyunaikare open up a new issue and post your composer.json file
