### ISSUE TITLE
ForbiddenHttpException() give error in backend(advanced template)

### ISSUE THREAD

**Issue by Abylaikhan** [amnah/yii2-user#148]
I add to backend controller method init()

```php
    public function init()
    {
        $user_id = Yii::$app->getUser()->id;
        if($user_id){
            $user = \amnah\yii2\user\models\User::findOne($user_id);
            if ($user->can("admin")) {

            }else{
                throw new ForbiddenHttpException();
            }
        }else{
            \Yii::$app->getResponse()->redirect(\Yii::$app->getUser()->loginUrl);
        }
        parent::init();
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                        'roles' => ['?'], // " ? " for guest user
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }`

```
but it gave error like this: An Error occurred while handling another error:
exception 'yii\web\ForbiddenHttpException' in C:\OpenServer\domains\yii2adv\backend\controllers\SiteController.php:28

How to solve it?

**Comment by amnah** [comment]
What's on line ```controllers\SiteController.php:28```?

Have you tried searching for that error? Take a look at this: http://stackoverflow.com/questions/32737621/yii2-error-occurs-while-throwing-notfoundexception

**Comment by Abylaikhan** [comment]
On 28 line this code:
`throw new ForbiddenHttpException();`
[http://stackoverflow.com/questions/32737621/yii2-error-occurs-while-throwing-notfoundexception](http://stackoverflow.com/questions/32737621/yii2-error-occurs-while-throwing-notfoundexception)

**Comment by amnah** [comment]
Looks like a routing issue. What url are you going to?

**Comment by Abylaikhan** [comment]
this url: http://yii2adv/backend/site/index
when i logged in like user i have an error above.

**Comment by amnah** [comment]
I'm not quite sure what the issue is, but I think it's a conflict between your custom ```init()``` check and the access rules in ```behaviors()```

Simplest solution would be to take out the access rules ```behaviors()```. There's no need for them if you're gonna always check for admin user anyway
