### ISSUE TITLE
Error after using CopyController: Missing required parameter "id" when instantiating "app\modules\user\Module".

### ISSUE THREAD

**Issue by MasteRus** [amnah/yii2-user#149]
Hello! I have a trouble:
I want to rewrite some parts of code in module, so I've complited all steps [of this instruction](https://github.com/amnah/yii2-user#i-need-more-control-can-i-just-extend-the-whole-thing), but i've get an error:
> Invalid Configuration – yii\base\InvalidConfigException
> Missing required parameter "id" when instantiating "app\modules\user\Module".

So what should I do to include new module correctly?

**Comment by amnah** [comment]
Did you set up the config properly? It should be in ```modules``` not ```components```

http://stackoverflow.com/questions/27729764/invalid-configuration-yii-base-invalidconfigexception/27730120#27730120
