### ISSUE TITLE
where should I put the setInfoFacebook($attributes) function?

### ISSUE THREAD

**Issue by cognitivaxx** [amnah/yii2-user#150]
I have the facebook registration working but i need use the setInfoFacebook($attributes) function in order to unificate the users with same email. 
Thanks

**Comment by amnah** [comment]
It goes to the ```AuthController```

https://github.com/amnah/yii2-user/blob/master/controllers/AuthController.php#L230-L254

**Comment by amnah** [comment]
Also, take a look at ```AuthController::attemptLogin()```. This already tries to match an existing user based on email.

https://github.com/amnah/yii2-user/blob/master/controllers/AuthController.php#L112-L173

**Comment by cognitivaxx** [comment]
You are big!
