### ISSUE TITLE
Object not found when I activated prettyUrl

### ISSUE THREAD

**Issue by gunturbudi** [amnah/yii2-user#154]
hey amnah, when i activated urlManager and enablePrettyUrl i cant found the /user/ route. But before i activated it, it works just fine.

**Comment by amnah** [comment]
Did you set up your vhost properly? http://www.yiiframework.com/doc-2.0/guide-start-installation.html#recommended-apache-configuration

And did you set ```'showScriptName' => false```? http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#using-pretty-urls

**Comment by gunturbudi** [comment]
Hey, i forgot the htaccess. Thanks amnah!
