### ISSUE TITLE
Yii::$app->user is not set properly. 

### ISSUE THREAD

**Issue by morguyus** [amnah/yii2-user#155]
Hello, just installed the package in a basic version of Yii2.
I have updated the config file config/web.php and config/db.php

When trying to load the module user I get following error: Yii::$app->user is not set properly. It needs to extend \amnah\yii2\user\components\User

Any ideas?

**Comment by amnah** [comment]
Did you set the user component?  https://github.com/amnah/yii2-user#installation

// app/config/web.php
return [
    'components' => [
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],
];
```

**Comment by morguyus** [comment]
Thanks, I forgot to change identityClass into class
