### ISSUE TITLE
AuthController. Social authorization.

### ISSUE THREAD

**Issue by vetal06** [amnah/yii2-user#156]
If username not Roman alphabet then user not saved. You can translit username and generation exception if user not saved in registerAndLoginUser function.

**Comment by amnah** [comment]
What is the error exactly? 

Have you tried setting your Yii2 app to UTF8 and mysql to utf8_unicode_ci?

**Comment by vetal06** [comment]
Yes. I use UTF8 . Model user not valide because  "[['username'], 'match', 'pattern' => '/^[A-Za-z0-9_]+$/u', 'message' => Yii::t('user', '{attribute} can contain only letters, numbers, and "_"')],". For example, this validation does not pass "Василий_Пупкин". You can use regular "/^\w+$/u"

**Comment by amnah** [comment]
Took a different route and removed validation for social auth scenario. I think this is best to prevent sudden errors, but users can still change the rules/translit username if they want to.

Thanks for the ```\w``` info.

fixed in 1e452e1da96a682f3f4509f579bf76a8ee2edaca
