### ISSUE TITLE
Unable to verify your data submission. 

### ISSUE THREAD

**Issue by 3dgroup** [amnah/yii2-user#159]
Sometimes when i login or logout i get this error "Unable to verify your data submission". i only get it on forms related to this module. I have the advanced app setup both on a different sub-domain and have different cookieValidationKeys. Sometimes i can login fine both other times not. Disabling CsrfValidation works but i am sure this shouldn't be the only way to fix the issue.

**Comment by amnah** [comment]
Hmm this is definitely a csrf issue, but I'm not sure why it would happen. The module doesn't have any custom code for csrf, it simply uses the built-in ```ActiveForm``` class.

Can you reproduce it consistently? 

It might be better to ask on the [yii2 forums](http://www.yiiframework.com/forum/index.php/forum/42-general-discussions/), someone there may have run into this issue before

**Comment by 3dgroup** [comment]
Well I wasn't sure if it was a Yii fault or module fault. The issue is very hit and miss but happens in development and server. Sometimes its fine sometimes it fails. I will post on Yii forum and get back to you.

**Comment by 3dgroup** [comment]
It looks like it was down to CSRF config
