### ISSUE TITLE
How to remove fields from profile table and add some custom?

### ISSUE THREAD

**Issue by GentleGoose** [amnah/yii2-user#160]
Hi, help me please. I can't remove "created_at" and "updated_at" from table profile, but I need to do this. When i remove these fields i receive error 
`Setting unknown property: amnah\yii2\user\models\Profile::created_at`
I tried to find a solution in model files, but have nothing. Help me please with this problem.

**Comment by amnah** [comment]
You need to remove the ```TimestampBehavior```

https://github.com/amnah/yii2-user/blob/master/models/Profile.php#L63-L76

```php
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'value' => function ($event) {
                    return gmdate("Y-m-d H:i:s");
                },
            ],
        ];
    }
```

**Comment by GentleGoose** [comment]
Thanks a lot for your feedback!
