### ISSUE TITLE
sendEmailConfirmation - generate only text in the email body

### ISSUE THREAD

**Issue by fpolito** [amnah/yii2-user#164]
Hello

I have made some little change in the file 
....\mail\confirmEmail.php

in order to generate a link and not a text in the body of the email, so now is faster because you only need to click on the link (instead with your code, the new user has to copy and paste the url)

this is the code:

<?php

use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var string $subject
 * @var \common\modules\user\models\User $user
 * @var \common\modules\user\models\Profile $profile
 * @var \common\modules\user\models\UserToken $userToken
 */
?>

`<h3>`<?= $subject ?>`</h3>`

`<p>`<?= Yii::t("user", "Please confirm your email address by clicking the link below:") ?>`</p>`
`<br/>`
`<p>`<?= Html::a(Url::toRoute(["/user/confirm", "token" => $userToken->token], true), Url::toRoute(["/user/confirm", "token" => $userToken->token], true)) ?>`</p>`

-----------------------------------------------------------
The same improvement should be done in the files:
- forgotPassword.php
- loginToken.php

bye bye
Francesco

**Comment by amnah** [comment]
Thanks for the suggestion!
