### ISSUE TITLE
packagist don`t update,come on

### ISSUE THREAD

**Issue by awebc** [amnah/yii2-user#167]
https://packagist.org/packages/amnah/yii2-user last update is at 2016-02-28 04:38 UTC

By composer , I can not get  your update content 

Please

**Comment by Katenkka** [comment]
I guess you need "dev-master" then - https://packagist.org/packages/amnah/yii2-user#dev-master

**Comment by amnah** [comment]
I've updated it, why not. I didn't realize it's been 8 months since the last release 

https://github.com/amnah/yii2-user/releases/tag/5.0.3

**Comment by awebc** [comment]
thanks,I see
