### ISSUE TITLE
this is a git submodule 

### ISSUE THREAD

**Issue by awebc** [amnah/yii2-user#173]
when git push code to my git repository with the vendor , amnah/yii2-user don`t be uploaded to my git repository .

what can i do ? I do not hope to composer again , because in china , to connect github.com very slow with composer . you know? what a pity!

**Comment by amnah** [comment]
Ummm, sorry but I don't really know much about submodules ... :(

You may want to try composer issues https://github.com/composer/composer/issues

Or maybe a php help forum https://www.reddit.com/r/PHPhelp/
