### ISSUE TITLE
[deadend] email registration workflow

### ISSUE THREAD

**Issue by 1Luc1** [amnah/yii2-user#182]
There seems to be an "deadend" when using the Login page v2 (login/register via email link) action.

**Workflow to reproduce**

1. Register with email (http://yii2.amnahdev.com/user/login-email)
2. Check Email -> new Email in Inbox
3. Click on Link in Email (index.php?r=user%2Flogin-callback&token=Cc99zf9GVBpc4h4oP4MX3yxS3iKTBUxj)
4. Enter Username and Fullname, hit button register
5. User is automatically logged in -> everything fine so far
5.1. BUT, **password isn't set** so far -> user has to go to profile page to set user
5.2. WHAT if user logs out? No password was set ...
5.3. User can use "reset password"; to actually set password, but thats kind of awkward

**Solution**
Add a password field to the login-callback view. First time user opens the login-callback link, he enters username, fullname and **password**.

**Comment by amnah** [comment]
You log in again by going to http://yii2.amnahdev.com/user/login-email

The entire point is to *not* have to enter a password at all. This functionality was copied from https://medium.com/, but of course you're free to modify it as needed to fit your business requirements

**Comment by 1Luc1** [comment]
Ok thank you for your response. It seems i misunderstood the logic behind this functionality. Thanks anyway for clarification.
