### ISSUE TITLE
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'm150214_044831_in it_user' not found'

### ISSUE THREAD

**Issue by mdtaher** [amnah/yii2-user#184]
$ yii migrate --migrationPath=@vendor/amnah/yii2-user/migrations
Yii Migration Tool (based on Yii v2.0.11.2)

Total 1 new migration to be applied:
        m150214_044831_init_user

Apply the above migration? (yes|no) [no]:yes
*** applying m150214_044831_init_user
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'm150214_044831_in
it_user' not found'

in C:\wamp\www\cpm\vendor\yiisoft\yii2\console\controllers\MigrateController.php
:192

Stack trace:
#0 C:\wamp\www\cpm\vendor\yiisoft\yii2\console\controllers\BaseMigrateController
.php(166): yii\console\controllers\BaseMigrateController->migrateUp()
#1 C:\wamp\www\cpm\vendor\yiisoft\yii2\base\InlineAction.php(57): yii\console\co
ntrollers\BaseMigrateController->actionUp()
#2 C:\wamp\www\cpm\vendor\yiisoft\yii2\base\InlineAction.php(57): ::call_user_fu
nc_array:{C:\wamp\www\cpm\vendor\yiisoft\yii2\base\InlineAction.php:57}()
#3 C:\wamp\www\cpm\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\Inline
Action->runWithParams()
#4 C:\wamp\www\cpm\vendor\yiisoft\yii2\console\Controller.php(128): yii\base\Con
troller->runAction()
#5 C:\wamp\www\cpm\vendor\yiisoft\yii2\base\Module.php(523): yii\console\Control
ler->runAction()
#6 C:\wamp\www\cpm\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Mo
dule->runAction()
#7 C:\wamp\www\cpm\vendor\yiisoft\yii2\console\Application.php(147): yii\console
\Application->runAction()
#8 C:\wamp\www\cpm\vendor\yiisoft\yii2\base\Application.php(392): yii\console\Ap
plication->handleRequest()
#9 C:\wamp\www\cpm\yii(27): yii\base\Application->run()
#10 {main}

**Comment by vastagricsi** [comment]
In **vendor/amnah/yii2-user/migrations/m150214_044831_init_user.php** i deleted namespace and "use Yii;"lines, then it works fine.

**Comment by amnah** [comment]
Ah damn, that was from a pull request a month ago - I assumed it was needed after a Yii update or something.

https://github.com/amnah/yii2-user/commit/969757e93f67ca4f83cdca1baa93b63d39e0e2ac

I'll double check and fix it when I get home tonight, thanks for the heads up.

**Comment by mdtaher** [comment]
Thanks **vastagricsi** for help, it worked as you said:)

**Comment by vastagricsi** [comment]
I'm glad to help. :)
