### ISSUE TITLE
i get error after click update user

### ISSUE THREAD

**Issue by testniger** [amnah/yii2-user#190]
https://yii2.amnahdev.com/user/admin/update?id=23 - link

Error
Call to a member function load() on null

`1. in /var/www/yii2/vendor/amnah/yii2-user/controllers/AdminController.php at line 130
 public function actionUpdate($id)
    {
        // set up user and profile
        $user = $this->findModel($id);
        $user->setScenario("admin");
        $profile = $user->profile;
 
        $post = Yii::$app->request->post();
        $userLoaded = $user->load($post);
        $profile->load($post);
 
        // validate for ajax request
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($user, $profile);
        }
 
        // load post data and validate
        if ($userLoaded && $user->validate() && $profile->validate()) {
`

**Comment by amnah** [comment]
woops was db issue, missing old data. thx
