### ISSUE TITLE
View

### ISSUE THREAD

**Issue by des1roer** [amnah/yii2-user#193]
// app/config/web.php
		'components' => [
		    'view' => [
		        'theme' => [
		            'pathMap' => [
		                '@vendor/amnah/yii2-user/views' => '@app/views/user', // example: @app/views/user/default/login.php
		            ],
		        ],
		    ],
		],

not work

**Comment by amnah** [comment]
what do you mean it doesnt work?
 after you put that into your config file, did you copy/paste the files from `@vendor/amnah/yii2-user/views` into `@app/views/user`? what does your directory structure look like

**Comment by des1roer** [comment]
![image](https://user-images.githubusercontent.com/10970793/27292071-a280a1b8-552b-11e7-8f9c-6f81a647ed7d.png)
****

**Comment by amnah** [comment]
hmm yea looks right. whats the error?

**Comment by amnah** [comment]
oh i think you're missing the `default`  folder 

    @app/views/user/default/login.php
