### ISSUE TITLE
Custom UserAuth model

### ISSUE THREAD

**Issue by gunnar-rikardsson** [amnah/yii2-user#194]
Hi there, and thanks for a good module.

I needed to customize the UserAuth model and changed model through my config for the module's  modelClasses property.
But in model User class, this change is not taken into account.
See model User class line 231-233.
I assume there should be a
$userAuth = $this->module->model("UserAuth");  
before the return statement.
In the same way as for other models, e.g. UserTokens.

regards
Gunnar

**Comment by amnah** [comment]
Yes, you're right - I've updated it e9396f03aae75dd3a1f938c10f2f7f4dc32f759b

I also made a new minor release https://github.com/amnah/yii2-user/releases/tag/5.0.7

Thanks!
