### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Yii' not found in /Applications/XAMPP/xamppfiles/htdocs/pegy_Yii2_App/basic/vendor/2amigos/yii2-usuario/src/User/resources/views/registration/register.php:22 Stack trace: #0 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/pegy_Yii2_App/basic/vendor/2amigos/yii2-usuario/src/User/resources/views/registration/register.php on line 22

### ISSUE THREAD

**Issue by erbus1** [amnah/yii2-user#196]
[register.php.zip](https://github.com/amnah/yii2-user/files/1402878/register.php.zip)

I can not see why it gives me this error. Thx for helping

**Comment by amnah** [comment]
Sorry but I don't know anything that module. You should ask them directly 

https://github.com/2amigos/yii2-usuario/issues
