### ISSUE TITLE
sendRecoverypassword gets exception 'yii\web\NotAcceptableHttpException' 

### ISSUE THREAD

**Issue by mavs1971** [amnah/yii2-user#199]
I use yii2-user and it was working fine until last week, that start to throw a exception #406... in logs file i have 

exception 'yii\web\NotAcceptableHttpException' with message 'Ha ocurrido un error ' in D:\matarile\clubs\vendor\abhi1693\yii2-user\models\AccountRecoverPasswordForm.php:51
Stack trace:
#0 D:\matarile\clubs\vendor\abhi1693\yii2-user\controllers\RecoveryController.php(54): abhimanyu\user\models\AccountRecoverPasswordForm->recoverPassword()
#1 [internal function]: abhimanyu\user\controllers\RecoveryController->actionRecoverPassword()
#2 D:\matarile\clubs\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#3 D:\matarile\clubs\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#4 D:\matarile\clubs\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction('recover-passwor...', Array)
#5 D:\matarile\clubs\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('user/recovery/r...', Array)
#6 D:\matarile\clubs\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 D:\matarile\clubs\index.php(18): yii\base\Application->run()
#8 {main}

the config file i have

 'mail' => 
    array (
      'class' => 'yii\\swiftmailer\\Mailer',
      'transport' => 
      array (
        'class' => 'Swift_SmtpTransport',
        'host' => 'smtp.gmail.com',
        'username' => 'myemail@gmail.com',
        'password' => 'mypassword',
        'port' => '465',
        'encryption' => 'ssl',
      ),
    ),

**Comment by amnah** [comment]
sorry but I'm not familiar with that module. you'll have to ask them
directly

https://github.com/abhi1693/yii2-user/issues?q=is%3Aopen+is%3Aissue
