### ISSUE TITLE
View file not found 

### ISSUE THREAD

**Issue by dtmw8z** [amnah/yii2-user#213]
![image](https://user-images.githubusercontent.com/45184540/81570436-7ece9000-9398-11ea-9bbd-0a1ce8086008.png)

Done all the config according to the instructions given but It gives error when I try to access \user\login. Even enabled preety urls.
Is there different way to access if I have theming enabled?

**Comment by amnah** [comment]
whats the entire error message? what does your config look like?

**Comment by dtmw8z** [comment]
[screencapture-localhost-wd-finalproject-group-25-web-user-login-2020-05-11-15_37_33.pdf](https://github.com/amnah/yii2-user/files/4610202/screencapture-localhost-wd-finalproject-group-25-web-user-login-2020-05-11-15_37_33.pdf)






my error is this.....

in my web i have this config:


<?php

$params = require __DIR__ . '/params.php';
$db = require __DIR__ . '/db.php';

$config = [
    'id' => 'basic',
    'name' => 'TDOT',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
    ],
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'Sbrdz9G87wYQkSSw9uxPdzkH_gIYU_Ss',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],

        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => true,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => $db,
        'view'=>[
            'theme' => [
                'basePath' => '@webroot/themes/custom',
                'baseUrl' => '@web/themes/custom',
            ],
        ],
        'urlManager' => [

            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [

            ],
        ],
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],

    ],
    'modules' => [
        'gridview' =>  [
            'class' => '\kartik\grid\Module'
            // enter optional module parameters below - only if you need to
            // use your own export download action or custom translation
            // message source
            // 'downloadAction' => 'gridview/export/download',
            // 'i18n' => []
        ],
        'user' => [
            'class' => 'amnah\yii2\user\Module',
            // set custom module properties here ...
            'requireEmail' => false,
            'requireUsername' => true

        ],

    ],

    'params' => $params,
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
        // uncomment the following to add your IP if you are not connecting from localhost.
        //'allowedIPs' => ['127.0.0.1', '::1'],
    ];

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        // uncomment the following to add your IP if you are not connecting from localhost.
        //'allowedIPs' => ['127.0.0.1', '::1'],
    ];
}

return $config;

**Comment by dtmw8z** [comment]
<?php

$params = require __DIR__ . '/params.php';
$db = require __DIR__ . '/db.php';

$config = [
    'id' => 'basic',
    'name' => 'TDOT',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
    ],
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'Sbrdz9G87wYQkSSw9uxPdzkH_gIYU_Ss',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],

        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => true,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => $db,
        'view'=>[
            'theme' => [
                'basePath' => '@webroot/themes/custom',
                'baseUrl' => '@web/themes/custom',
            ],
        ],
        'urlManager' => [

            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [

            ],
        ],
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],

    ],
    'modules' => [
        'gridview' =>  [
            'class' => '\kartik\grid\Module'
            // enter optional module parameters below - only if you need to
            // use your own export download action or custom translation
            // message source
            // 'downloadAction' => 'gridview/export/download',
            // 'i18n' => []
        ],
        'user' => [
            'class' => 'amnah\yii2\user\Module',
            // set custom module properties here ...
            'requireEmail' => false,
            'requireUsername' => true

        ],

    ],

    'params' => $params,
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
        // uncomment the following to add your IP if you are not connecting from localhost.
        //'allowedIPs' => ['127.0.0.1', '::1'],
    ];

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        // uncomment the following to add your IP if you are not connecting from localhost.
        //'allowedIPs' => ['127.0.0.1', '::1'],
    ];
}

return $config;

**Comment by amnah** [comment]
try adding this `pathMap` as well

```
'components' => [
    'view' => [
        'theme' => [
            'pathMap' => [
                '@vendor/amnah/yii2-user/views' => '@app/views/user', // example: @app/views/user/default/login.php
            ],
        ],
    ],
],
```

**Comment by amnah** [comment]
actually this might just be because of your weird view theme. you may need to customize the layout param

> Because layouts are also views, they can be created in the similar way as normal views. By default, layouts are stored in the directory @app/views/layouts. For layouts used within a module, they should be stored in the views/layouts directory under the module directory. You may customize the default layout directory by configuring the yii\base\Module::$layoutPath property of the application or modules.


https://www.yiiframework.com/doc/guide/2.0/en/structure-views#layouts

**Comment by dtmw8z** [comment]
Okay...This may help me....I will try this.....Thanks

**Comment by dtmw8z** [comment]
If anyone gets here in future, This was actually caused by not having the main layout as main.php (we had it as base.php). And as layouts are also views so it says view file not fould. 
So, just rename your main layout to main.php and it will work.

Great work by the developer .. 

Thank you
