### ISSUE TITLE
Field name 'key' should be avoided as it is a reserved keyword (MySQL)

### ISSUE THREAD

**Issue by drsdre** [amnah/yii2-user#27]
In table definition:
$this->createTable(UserKey::tableName(), [
            "id" => "int unsigned not null auto_increment primary key",
            "user_id" => "int unsigned not null",
            "type" => "tinyint not null",
---->     "key" => "varchar(255) not null",
            "create_time" => "timestamp null default null",
            "consume_time" => "timestamp null default null",
            "expire_time" => "timestamp null default null",
        ]);

My suggestion would be to change field name to 'keyname'.

**Comment by amnah** [comment]
fixed in https://github.com/amnah/yii2-user/commit/5e43a60eff8c5ebd5c820f002b13b737ba281296
