### ISSUE TITLE
Rbac support to User model

### ISSUE THREAD

**Issue by Patroklo** [amnah/yii2-user#42]
Hi! I have started learning yii2 a week ago and I saw your auth extension (very interesting, I think that I'll use it as default user management in my little projects while I learn this framework). But I saw that you can't use rbac roles in the user objects, I think that it doesn't have a lot of sense while with the User component you can do that, so I have added into my fork some changes into the can() method to fix that. 

Are you interested in sending you a pull request with the changes to add this support to the main branch of the project?

thanks!

**Comment by taufikherjanto** [comment]
How to implement use rbac in amnah/yii2-user, this documentation can't explain clearly
