### ISSUE TITLE
Cannot delete user because (Integrity constraint violation: 1451) foreign  dependency key .  table 'user', table 'role'

### ISSUE THREAD

**Issue by wmfunk** [amnah/yii2-user#43]
Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`db1`.`user_key`, CONSTRAINT `user_key_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`))
The SQL being executed was: DELETE FROM `user` WHERE `id`=4

Error Info: Array
(
    [0] => 23000
    [1] => 1451
    [2] => Cannot delete or update a parent row: a foreign key constraint fails (`db1`.`user_key`, CONSTRAINT `user_key_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`))
)

↵
Caused by: PDOException
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`db1`.`user_key`, CONSTRAINT `user_key_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`))

in /var/www/encounter/vendor/yiisoft/yii2/db/Command.php at line 768

**Comment by saurabhhandysolver** [comment]
This error can be solved by setting up 'on delete'  in parent table  to 'set null'. because if you are deleting a row from child table than the field/column which is used in parent table by a foreign key that should be null on delete.

user_id should be null on delete.

**Comment by jayalanaa** [comment]
yes

**Comment by jayalanaa** [comment]
in yii2 how to delete foreign key constraint  records both table records

**Comment by amnah** [comment]
use https://www.yiiframework.com/doc/api/2.0/yii-db-migration#dropForeignKey()-detail
