### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by comarcat** [amnah/yii2-user#45]
Im trying to install yii2-user on my Yii2 basic Project but when i try to use Composer the error is:

[InvalidArgumentException]
There are no commands defined in the "amnah/yii2-user" namespace.

Or when I try to downlad the zip file and extrac into vendor folder the error is:

Class amnah\yii2\user\components\User does not exist

Maybe im doing the wrong steps but I followed the guides.

The last error is on Yii Migrate command:

*** applying m140524_153638_init_user
Exception 'PDOException' with message 'SQLSTATE[42000]: [Microsoft][SQL Server N
ative Client 11.0][SQL Server]A transaction that was started in a MARS batch is
still active at the end of the batch. The transaction is rolled back.'

in C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\db\mssql\PDO.php:36

Stack trace:
#0 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\db\mssql\PDO.php(36): PDO->exec('BEGIN TRANSACTI...')
#1 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\db\Transaction.php(119): yii\db\mssql\PDO->beginTransaction()
#2 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\db\Connection.php(639): yii\db\Transaction->begin(NULL)
#3 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\db\Migration.php(76): yii\db\Connection->beginTransaction()
#4 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(488): yii\db\Migration->up()
#5 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(126): yii\console\controllers\BaseMigrateController->migrateUp('m140524_153638_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#8 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#9 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\console\Controller.php(91): yii\base\Controller->runAction('', Array)
#10 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\base\Module.php(455): yii\console\Controller->runAction('', Array)
#11 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\console\Application.php(161): yii\base\Module->runAction('migrate', Array)
#12 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\console\Application.php(137): yii\console\Application->runAction('migrate', Array)
#13 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 C:\Users\omaarbte\Documents\My Web Sites\Yii2B\yii(23): yii\base\Application->run()
#15 {main}

**Comment by abhimanyunaikare** [comment]
where on earth did you did those updates dear? Please
