### ISSUE TITLE
Forbidden (#403)

### ISSUE THREAD

**Issue by epulgaron** [amnah/yii2-user#52]
when i try acces to /user/admin i get this error, what happend?

**Comment by dyar74** [comment]
I am login with neo/neo and have this error too.

**Comment by amnah** [comment]
can you provide more details please

**Comment by dyar74** [comment]
basic app, install rbac. Login with neo/neo. And have Forbidden (#403) .

**Comment by amnah** [comment]
does it work if you have out rbac?

**Comment by amnah** [comment]
does it work if you take out rbac?

**Comment by dyar74** [comment]
Sorry, but i don't have some time and now i remove this extension. May be I install it later and test this extension. Thank you!
