### ISSUE TITLE
Fails to login after fresh installation

### ISSUE THREAD

**Issue by randaelayan** [amnah/yii2-user#55]
Thank you for the great module.

I am trying to login using neo/neo but i get Incorrect username or password.

**Comment by amnah** [comment]
Sorry, been a bit busy with my new job lately. Did you ever figure out what was wrong?

**Comment by randaelayan** [comment]
No.

On Thu, Jan 22, 2015 at 7:35 AM, amnah <notifications@github.com> wrote:

> Sorry, been a bit busy with my new job lately. Did you ever figure out
> what was wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amnah/yii2-user/issues/55#issuecomment-70970339>.
>



-- 
Regards,
Randa Elayan

**Comment by Draven714** [comment]
I am also having this issue.

**Comment by randaelayan** [comment]
I have made the installation all over once again,when I login I am still
anonymous without any errors.

On Tue, Feb 3, 2015 at 11:03 PM, Michael Delle <notifications@github.com>
wrote:

> I am also having this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amnah/yii2-user/issues/55#issuecomment-72800714>.
>



-- 
Regards,
Randa Elayan

**Comment by randaelayan** [comment]
I am trying to debug, I registered a new user, and edited the status from
DB to be 10.

When I login, I get the error

Unknown Method – yii\base\UnknownMethodException
<http://www.yiiframework.com/doc-2.0/yii-base-unknownmethodexception.html>Calling
unknown method: common\models\User::getDisplayName()

Isn't it should be amnah/../user not
common\models\User?

I printed the user object and got

common\models\User Object
(...


On Mon, Feb 16, 2015 at 4:48 AM, Randa Elayan <randa.elayan@gmail.com>
wrote:

> I have made the installation all over once again,when I login I am still
> anonymous without any errors.
>
> On Tue, Feb 3, 2015 at 11:03 PM, Michael Delle <notifications@github.com>
> wrote:
>
>> I am also having this issue.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/amnah/yii2-user/issues/55#issuecomment-72800714>.
>>
>
>
>
> --
> Regards,
> Randa Elayan
>



-- 
Regards,
Randa Elayan

**Comment by amnah** [comment]
looks like you're using the advanced app. are you sure you're setting the
correct user component?

it should be changed in frontend/config/main.php and
backend/config/main.php (not common/config)

**Comment by amnah** [comment]
I actually pushed a recent change that checks this directly. can you do a
composer update and then try again?

if it throws an error then it's definitely a config issue

**Comment by randaelayan** [comment]
I updated, I tried to login with neo / neo, and I got incorrect password.

Then I tried to signup with a new user, and I got


On Tue, Feb 17, 2015 at 10:31 AM, amnah <notifications@github.com> wrote:

> I actually pushed a recent change that checks this directly. can you do a
> composer update and then try again?
>
> if it throws an error then it's definitely a config issue
>
> On Feb 17, 2015 1:23 PM, "amnah" <amnahx@gmail.com> wrote:
>
> > looks like you're using the advanced app. are you sure you're setting the
> > correct user component?
> >
> > it should be changed in frontend/config/main.php and
> > backend/config/main.php (not common/config)
> > On Feb 17, 2015 8:36 AM, "randaelayan" <notifications@github.com> wrote:
> >
> >> I am trying to debug, I registered a new user, and edited the status
> from
> >> DB to be 10.
> >>
> >> When I login, I get the error
> >>
> >> Unknown Method – yii\base\UnknownMethodException
> >> <
> http://www.yiiframework.com/doc-2.0/yii-base-unknownmethodexception.html
> >> >Calling
> >> unknown method: common\models\User::getDisplayName()
> >>
> >> Isn't it should be amnah/../user not
> >> common\models\User?
> >>
> >> I printed the user object and got
> >>
> >> common\models\User Object
> >> (...
> >>
> >>
> >> On Mon, Feb 16, 2015 at 4:48 AM, Randa Elayan <randa.elayan@gmail.com>
> >> wrote:
> >>
> >> > I have made the installation all over once again,when I login I am
> still
> >> > anonymous without any errors.
> >> >
> >> > On Tue, Feb 3, 2015 at 11:03 PM, Michael Delle <
> >> notifications@github.com>
> >> > wrote:
> >> >
> >> >> I am also having this issue.
> >> >>
> >> >> —
> >> >> Reply to this email directly or view it on GitHub
> >> >> <https://github.com/amnah/yii2-user/issues/55#issuecomment-72800714
> >.
> >> >>
> >> >
> >> >
> >> >
> >> > --
> >> > Regards,
> >> > Randa Elayan
> >> >
> >>
> >>
> >>
> >> --
> >> Regards,
> >> Randa Elayan
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/amnah/yii2-user/issues/55#issuecomment-74668143>.
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amnah/yii2-user/issues/55#issuecomment-74722813>.
>



-- 
Regards,
Randa Elayan

**Comment by randaelayan** [comment]
I updated, I tried to login with neo / neo, and I got incorrect password.

Then I tried to signup with a new user, and I got
Unknown Property – yii\base\UnknownPropertyException
<http://www.yiiframework.com/doc-2.0/yii-base-unknownpropertyexception.html>Setting
unknown property: common\models\User::password_hash

On Fri, Feb 20, 2015 at 4:54 AM, Randa Elayan <randa.elayan@gmail.com>
wrote:

> I updated, I tried to login with neo / neo, and I got incorrect password.
>
> Then I tried to signup with a new user, and I got
>
>
> On Tue, Feb 17, 2015 at 10:31 AM, amnah <notifications@github.com> wrote:
>
>> I actually pushed a recent change that checks this directly. can you do a
>> composer update and then try again?
>>
>> if it throws an error then it's definitely a config issue
>>
>> On Feb 17, 2015 1:23 PM, "amnah" <amnahx@gmail.com> wrote:
>>
>> > looks like you're using the advanced app. are you sure you're setting
>> the
>> > correct user component?
>> >
>> > it should be changed in frontend/config/main.php and
>> > backend/config/main.php (not common/config)
>> > On Feb 17, 2015 8:36 AM, "randaelayan" <notifications@github.com>
>> wrote:
>> >
>> >> I am trying to debug, I registered a new user, and edited the status
>> from
>> >> DB to be 10.
>> >>
>> >> When I login, I get the error
>> >>
>> >> Unknown Method – yii\base\UnknownMethodException
>> >> <
>> http://www.yiiframework.com/doc-2.0/yii-base-unknownmethodexception.html
>> >> >Calling
>> >> unknown method: common\models\User::getDisplayName()
>> >>
>> >> Isn't it should be amnah/../user not
>> >> common\models\User?
>> >>
>> >> I printed the user object and got
>> >>
>> >> common\models\User Object
>> >> (...
>> >>
>> >>
>> >> On Mon, Feb 16, 2015 at 4:48 AM, Randa Elayan <randa.elayan@gmail.com>
>> >> wrote:
>> >>
>> >> > I have made the installation all over once again,when I login I am
>> still
>> >> > anonymous without any errors.
>> >> >
>> >> > On Tue, Feb 3, 2015 at 11:03 PM, Michael Delle <
>> >> notifications@github.com>
>> >> > wrote:
>> >> >
>> >> >> I am also having this issue.
>> >> >>
>> >> >> —
>> >> >> Reply to this email directly or view it on GitHub
>> >> >> <https://github.com/amnah/yii2-user/issues/55#issuecomment-72800714
>> >.
>> >> >>
>> >> >
>> >> >
>> >> >
>> >> > --
>> >> > Regards,
>> >> > Randa Elayan
>> >> >
>> >>
>> >>
>> >>
>> >> --
>> >> Regards,
>> >> Randa Elayan
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub
>> >> <https://github.com/amnah/yii2-user/issues/55#issuecomment-74668143>.
>> >>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/amnah/yii2-user/issues/55#issuecomment-74722813>.
>>
>
>
>
> --
> Regards,
> Randa Elayan
>



-- 
Regards,
Randa Elayan

**Comment by sheershoff** [comment]
I've found the following behavior, which could have lead to the error.

In a fresh installation in exception rendering page the login link points to '/site/login', not to the '/user/login', so, having in mind, that '/site/login' is not part of the module, the login form at the link doesn't work as expected and throws 'unknown property: common\models\User::password_hash'. It took me 20 minutes to realize that :-)

**Comment by amnah** [comment]
Well, he mentioned before that he's using the correct link ... In either case, something is wrong as it shouldn't be calling ```common\models\User```. 

@randaelayan Can you list the exact steps you took? From installing yii2-app-advanced to getting the error.

**Comment by randaelayan** [comment]
Yes,I am using the advanced App, and as you mentioned in your installation
note:

// NOTE: in the yii2-advanced-app, the user component should be
updated in        // 'frontend/config/main.php' and/or
'backend/config/main.php' (OR you can add it        // to
'common/config' if you remove it from frontend/backend)        'user'
=> [            'class' => 'amnah\yii2\user\components\User',
],


I did  put it in common/config, but didn't remove it from frontend and
backend...

That was the problem.

Thank you

And really appreciating your efforts in this plugin.

On Mon, Feb 23, 2015 at 10:39 PM, amnah <notifications@github.com> wrote:

> Reopened #55 <https://github.com/amnah/yii2-user/issues/55>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amnah/yii2-user/issues/55#event-240440028>.
>



-- 
Regards,
Randa Elayan

**Comment by amnah** [comment]
Nice! Glad you were able to figure it out.
