### ISSUE TITLE
Undefined index $attributes['email']

### ISSUE THREAD

**Issue by o-shabashov** [amnah/yii2-user#56]
https://www.dropbox.com/s/c2yugtr4qf8uf57/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-01-17%2020.55.16.png?dl=0

**Comment by amnah** [comment]
Hmm, what versions are you using? i just set up a new app from scratch and it worked properly.

Yii 2.0.3-dev
Yii 2 User Module - 2.1.0

Can you do a ```print_r($attributes)``` and see what kind of data you're getting? (I think perhaps you have more than one email address)

Unfortunately busy this weekend and can't test until probably Tuesday

**Comment by o-shabashov** [comment]
This is from your demo site :)

**Comment by amnah** [comment]
Hmm can't replicate, even after adding in a second email address. Don't really know how else to debug this, so I added in a quick hack to dump the ```$attributes```.

Would you mind trying again please?

http://yii2.amnahdev.com/user/login

**Comment by o-shabashov** [comment]
https://www.dropbox.com/s/wbc4meci80tfuxk/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-01-25%2018.23.03.png?dl=0

**Comment by amnah** [comment]
I have no idea how your account exists without an email lol. I signed up for a new gmail/facebook account, but the popup window asked me to confirm it instead of outputting an error...

**Comment by amnah** [comment]
Oh! Did you by any chance sign up using a phone number instead of an email?

**Comment by o-shabashov** [comment]
Hi! Sign up where - Facebook or your demo?

**Comment by amnah** [comment]
Sorry, I meant facebook. I read that if you sign up on Facebook with a
phone number, then there's no email address.  Wanted to see if that was the
case with you.

**Comment by o-shabashov** [comment]
I already sign up in facebook by phone number and then trying to login on your demo. And yes, seems my FB account doesn't have email.

**Comment by amnah** [comment]
So I updated it to check both email and username. I guess since yours doesn't have either, it'll try making a username out of your name. 

Would you mind quickly trying it out again please?

http://yii2.amnahdev.com/user/login

**Comment by o-shabashov** [comment]
Yeap, its work now!
https://www.dropbox.com/s/h75scb7vaki0ogp/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-01-29%2010.44.55.png?dl=0

Thanks man!
