### ISSUE TITLE
Should social login/register work on localhost?

### ISSUE THREAD

**Issue by con322** [amnah/yii2-user#57]
Sorry if it's a stupid question but off a noob with yii framework and social login.register.

Should it work on local host or does it have to be on a live server to test?

Also the code `protected function setInfoFacebook` which directory/file should that be put in?

Thanks & Awesome Work :+1:

**Comment by amnah** [comment]
It works on localhost. Just make a facebook app and make sure to set ```Site Url``` and ```Mobile Site Url``` to *http://localhost/*

For ```setInfoFacebook```, you'll want to [extend and override](https://github.com/amnah/yii2-user#how-do-i-extend-this-package) the function in [AuthController](https://github.com/amnah/yii2-user/blob/master/controllers/AuthController.php#L242)

**Comment by con322** [comment]
Okay thanks, bit of a noob with yii framwork so finding it a bit confusing on where to put some of the code etc.

Say I am wanting to prevent all users apart from admin accessing the admin crud interface how'd i do that?

I can see there's the follow in code in the wiki (does the below code go in the User model.

````

if (!Yii::$app->user->can("admin")) {
    throw new HttpException(403, 'You are not allowed to perform this action.');
}
// --- or ----
$user = User::findOne(1);
if ($user->can("admin")) {
    // do something
};

````

**Comment by amnah** [comment]
That's actually already built in - check the [AdminController](https://github.com/amnah/yii2-user/blob/master/controllers/AdminController.php#L22).

**Comment by con322** [comment]
Awesome apologies about that just discovering things. That's cool, so if i wanted to create another role for example legitUser or something I would create a new column in the database.Where would I apply the rules for that user as it wouldn't be within the vendor directory where the current rules etc for admin / user are currently. Would I create an admin controller and then extend or would I put the code in User model?

**Comment by amnah** [comment]
No need to apologize, it's great that you're putting in the effort to learn this stuff.

For your question, you can create a role by adding a record to the `role` table. Then to add specific permissions, add a `can_xxxxxxx` column. 

For using the rules, you can put it pretty much anywhere. Typically the controller is fine, but it's hard to say without knowing what you're trying to do.

**Comment by con322** [comment]
Basically I want three roles which I have now added a col in the table and a row for the new user.

Admin - Can do everything
User - Can post, update & delete however posts must be approved
Legit User  - Can post without needing to be approved, as well as having access to other pages/forms etc that a normal user cannot.

Do I just put the function I want a user to be able to perform with an if statement? (just trying to understand how yii2 user works & yii in general)

**Comment by amnah** [comment]
Please see the [extending](https://github.com/amnah/yii2-user#how-do-i-extend-this-package) section in the readme. You basically need to create classes/view that extends the built-in class/views.

For your example, I would add a field into the ```role``` table - ```role.can_autopost```. Then you can just check it in the controller:

```php
public function actionPost()
{
    // do validation and stuff
    if ($user->can('autopost') {
        $post->status = 'pending';
    } else {
        $post->status = 'approved';
    }
}
```

**Comment by con322** [comment]
Thanks for the help that's awesome, I thought along thoselines so thanks for confirming :+1:
