### ISSUE TITLE
advanced template yii2

### ISSUE THREAD

**Issue by db012** [amnah/yii2-user#58]
Hi,
I've installed yii2 and I'm trying to customize the standard advanced app template. (https://github.com/yiisoft/yii2-app-advanced)
My project root is /var/www/html/advanced 
I've Apache2, PHP Version 5.5.9-1 on ubuntu4.5
I've correctly
-Install Yii 2 
-Install package via composer "amnah/yii2-user": "dev-master" which is in /www/html/advanced/vendor
-I've tried to modify 'frontend/config/main.php' and 'backend/config/main.php and below there is my first question
-I've run migration and all goes right; I've test the connection (via a testdb.php file) and I'm able to retrieve data (ID:1 username:neoemail: neo@neo.com)
-I Go to http://localhost/advanced/web/user or http://127.0.0.1/advanced/web/user, and the message is:
Not Found The requested URL /advanced/web/user was not found on this server. Apache/2.4.7 (Ubuntu) Server at 127.0.0.1 Port 80

First issue on point 3 of installation guide: 
all path in the guide is amnah\yii2\user (eg.'class' => 'amnah\yii2\user\components\User',) but 
in amnah folder user.php is in /amnah/yii2-user/components so yii2-user and no yii2\user 
Is correct to modify this path according to the right path?
My final path is so for
'class' => 'amnah\yii2\user\components\User' is
'class' => 'vendor\amnah\yii2-user\components\User'
is it right?

I've tried both path but I've got the same error.

Is there the path http://localhost/advanced/web/user correct? I've no folder web/user

Any idea?
Thank you for your support.

**Comment by amnah** [comment]
you may want to go back and read up more about the advanced app. you need
to handle the frontend/backend stuff

https://github.com/yiisoft/yii2-app-advanced#getting-started

so it's going to look something like "advanced/frontend/web/user/"

also you shouldn't be changing any of the namespaced classes, that's
constant

**Comment by db012** [comment]
Thank you for your answer. I decided to start from scratch, and I reinstall Yii 2 Advanced Application Template as explained in the "getting started" so I've http://127.0.0.1/backend and http://127.0.0.1/frontend link which are both working. 
Next step: I've installed your package via composer, updated frontend/config/main.php' and 'backend/config/main.php' without any change, create a new database, set the components['db'] configuration in common/config/main-local.php accordingly, and run migration.
But if I go to http://127.0.0.1/frontend/web/user or http://127.0.0.1/backend/web/user I've always the same error (Not Found The requested URL /frontend/web/user was not found on this server. - same error also for backend)
I'm sorry but I can't figured out where I'm wrong.
Thank you so much.

**Comment by amnah** [comment]
Did you figure out what was wrong? If not I can look into it tomorrow when I have some free time.

**Comment by db012** [comment]
Yes thank you so much.
I've:

Changed url links in frontend/views/layouts/main.php to point to /user/register and /user/login
$menuItems[] = ['label' => 'Signup', 'url' => ['/user/register']];
                $menuItems[] = ['label' => 'Login', 'url' => ['/user/login']];

Changed url links in backend/views/layouts/main.php to point /user/login

                $menuItems[] = ['label' => 'Login', 'url' => ['/user/login']];

and all goes on.
