### ISSUE TITLE
The configuration for the "extensions" component must contain a "class" element.

### ISSUE THREAD

**Issue by montyxrizzo** [amnah/yii2-user#63]
I am attempting to install this extension and the "Invalid Configuration – yii\base\InvalidConfigException" error keeps getting thrown. my config/web.php is 

       <?php

        $params = require(__DIR__ . '/params.php');
       // $config =[
       return [
       'id' => 'basic',
       'basePath' => dirname(__DIR__),
       'bootstrap' => ['log'],
       'components' => [
       'urlManager' => [
          // 'showScriptName' => false,
          // 'enablePrettyUrl' => true
                  ],    
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => '',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],

         'vendorPath' => dirname(dirname(DIR)) . '/vendor',
        'extensions' => require(DIR . '/../../vendor/yiisoft/extensions.php'),
        'components' => [
        'cache' => [
        'class' => 'yii\caching\FileCache',
        ],
        'user'=>[
        'class' => 'amnah\yii2\user\components\User',
        ]
        ],
        'modules' => [
        'user' => [
        'class' => 'amnah\yii2\user\Module',
        // set custom module properties here ...
        ],
           ],
             'errorHandler' => [
               'errorAction' => 'site/error',
            ],
            'mailer' => [
              'class' => 'yii\swiftmailer\Mailer',
              // 'useFileTransport' => true,
               // 'messageConfig' => [
               // 'from' => ['admin@website.com' => 'Admin'], // this is needed for sending emails
               'charset' => 'UTF-8',
               'useFileTransport' => true,
           ],

           'log' => [
               'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                    ],
                ],
            ],
            'db' => require(__DIR__ . '/db.php'),
           ],
       'params' => $params,
       ];

       if (YII_ENV_DEV) {
          // configuration adjustments for 'dev' environment
         $config['bootstrap'][] = 'debug';
         $config['modules']['debug'] = 'yii\debug\Module';

         $config['bootstrap'][] = 'gii';
         $config['modules']['gii'] = 'yii\gii\Module';
     }

return $config;

Any help would be greatly appreciated!

**Comment by amnah** [comment]
Umm... your config file looks pretty messed up. I'm not sure what happened here, looks like a vcs merge error or something. If you look carefully, you'll see that you have a *components* element inside of another *components* element ...

Also, you still have the *extensions* element [which was removed may 2014](https://github.com/yiisoft/yii2-app-basic/commit/b946b9906dc0bb56c8939bcc1ebe651cfbdae00c).

I'd recommended [starting from scratch again](https://github.com/yiisoft/yii2-app-basic/blob/master/config/web.php).

**Comment by amnah** [comment]
Oh, and don't forget to set that cookieValidationKey

```php
'request' => [
    // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
    'cookieValidationKey' => '',
],
```

**Comment by montyxrizzo** [comment]
Will do, I purposely removed the cookie key (sorry for not mentioning that) and thanks for the quick response, I'll try now!

**Comment by montyxrizzo** [comment]
with it just like this the error still gets thrown 




  <?php

$params = require(__DIR__ . '/params.php');

return [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => '4cKNlubX3ojS46GGGliJQZJ3AkARS0Y5',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],

         'user' => [
             'class' => 'amnah\yii2\user\components\User',
            'enableAutoLogin' => true,
        ],
        'modules' => [
        'user' => [
            'class' => 'amnah\yii2\user\Module',
            // set custom module properties here ...
         ],
         ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
           // 'useFileTransport' => true,
            // 'messageConfig' => [
            // 'from' => ['admin@website.com' => 'Admin'], // this is needed for sending emails
            'charset' => 'UTF-8',
            'useFileTransport' => true,
        ],

        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => require(__DIR__ . '/db.php'),
    ],
    'params' => $params,
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = 'yii\debug\Module';

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = 'yii\gii\Module';
}

return $config;

**Comment by amnah** [comment]
Getting close, but still a bit of misconfiguration. The "modules" part
needs go outside by one level, so it should be at the same level as the
"components".

**Comment by montyxrizzo** [comment]
You sir are a gentleman and a scholar! That was precisely my problem!!!! Thank you oh so very much!

**Comment by montyxrizzo** [comment]
only other small hiccup is on trying to migrate. I get this "PHP Fatal error:  Uncaught exception 'yii\base\InvalidConfigException' with message 'The "id" configuration for the Application is required.' in /Applications/MAMP/htdocs/nbound/vendor/yiisoft/yii2/base/Application.php:220"

**Comment by amnah** [comment]
Migrations use the config/console.php file, did you modify that a bit? Sounds like you just need to make sure the "id" is set.

See [sample](https://github.com/yiisoft/yii2-app-basic/blob/master/config/console.php)

**Comment by montyxrizzo** [comment]
That was the problem! Thanks again!!!
