### ISSUE TITLE
sqlite and foreign keys

### ISSUE THREAD

**Issue by phaag** [amnah/yii2-user#66]
It seems, as the migrate script is not sqlite3 compatible and its way, dealing with foreign keys.
foreign keys need to be added while creating a table in sqlite - adding afterwards is not supported.
Any way this to be fixed?

**Comment by amnah** [comment]
Hmm, I guess the easiest way is to just comment out the foreign key commands. Otherwise it looks like you might have to manually write out the sql queries to add in the foreign keys.

Something like [this](https://github.com/yiisoft/yii2-framework/blob/master/rbac/migrations/schema-sqlite.sql)

**Comment by phaag** [comment]
Thanks for the feedback. Yes - the setup of the DB works - however, there seem to be other issues.
Everything is set up, using your given script.
When I log in with neo/neo, I get the following error:

============
Database Exception – yii\db\Exception

SQLSTATE[HY000]: General error: 14 unable to open database file
The SQL being executed was: UPDATE `user` SET `login_time`='2015-01-31 17:55:05' WHERE `id`=1
Error Info: Array
(
    [0] => HY000
    [1] => 14
    [2] => unable to open database file
)
↵
Caused by: PDOException

SQLSTATE[HY000]: General error: 14 unable to open database file

in /var/www/html/devel/vendor/yiisoft/yii2/db/Command.php at line 768
=========

Looks like anything with the sqlite file is wrong. Checking permission - everything fine.
Re-enter the URL app/web/index.php - The App reappears - but interestingly enough, I'm logged in as neo/neo from what I see to right in the header. Next - logout from the app - works.
Then try to login with an invalid user bla/bla. Access is correctly denied - user not found. Retry neo/neo - again php error as described. It looks like it can verify the user but subsequently sql statements failed.
I get similar errors if I try to change my profile. User neo is not admin either - /usr/admin reports access denied.

Any hints?

Many thanks

- Peter

**Comment by phaag** [comment]
Addiing a screenshot to document the above ..
![debug](https://cloud.githubusercontent.com/assets/4414445/5992124/fa2b1f98-aa19-11e4-8e08-719e2313b99f.png)

**Comment by amnah** [comment]
Hmm seems like you can read but not write to the db. Quick google check says it's a permissions issue.

Try this and see if it helps:

https://github.com/yiisoft/yii2/issues/232#issuecomment-71972982

**Comment by phaag** [comment]
Thx. However, this is completely not understandable, why the directory needs to be rw. There is no reason for that ...

**Comment by amnah** [comment]
did it work?

**Comment by phaag** [comment]
Yes - it did! Many thanks!

**Comment by thecocce** [comment]
Hello, I have same "SQLSTATE[HY000]: General error: 14 unable to open database file " problem.
The migration command is done correctly. But I can't open sql file. 
Also specified Everybody full control on parent folder..

I use WAMP on Win8.1 machine.. 
Any ideas?

Thanks in advance

**Comment by amnah** [comment]
No idea ... Windows doesn't even have permissions like Linux/mac. Can you try a fresh installation?
