### ISSUE TITLE
Add a property to take available register feature

### ISSUE THREAD

**Issue by cesao** [amnah/yii2-user#68]
Hey guy, thanks a lot for your module, good job! It's save my time! 
However, I would suggest that you develop a property in your module to take available register feature, because sometimes we do not want the users make a signup by themselves.

**Comment by amnah** [comment]
I'm sorry, I don't quite understand. Can you please clarify?

**Comment by cesao** [comment]
No problem! The idea is to create a variable at module's class that means wheter anybody (a guest) can make a register or not. And at ActionRegister (https://github.com/amnah/yii2-user/blob/master/controllers/DefaultController.php) checks if a guest can make a register. For example, if variable is "false" only users "admin" can create a new user. Did you understand?

**Comment by amnah** [comment]
I think I understand ...

Yes, only guests can register a new account. However, admins can already create a user directly in their admin section (at ```http://website.com/user/admin/create```).

Is that what you mean?

**Comment by cesao** [comment]
Kiind of. I want that only admin user can create a new user, but it be optional. Sometimes guests can register a new account and other times just admin user can do it.

**Comment by amnah** [comment]
Ahhh ok, I see. Well, this is a very specific case, so I recommend you just do it yourself. It takes only a minute to [extend](https://github.com/amnah/yii2-user#how-do-i-extend-this-package) the Module and add it in.
