### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Draven714** [amnah/yii2-user#69]
Trying to login using neo/neo but it's not working. It's not giving an error or anything. The page refreshes (username and password are removed from the form).

Here is the log:

	07:52:09.123	trace	yii\base\Application::bootstrap	Bootstrap with yii\log\Dispatcher
	07:52:09.123	trace	yii\base\Module::getModule	Loading module: debug
	07:52:09.126	trace	yii\base\Application::bootstrap	Bootstrap with yii\debug\Module::bootstrap()
	07:52:09.127	trace	yii\base\Module::getModule	Loading module: gii
	07:52:09.127	trace	yii\base\Application::bootstrap	Bootstrap with yii\gii\Module::bootstrap()
	07:52:09.128	trace	yii\web\UrlManager::parseRequest	Pretty URL not enabled. Using default URL parsing logic.
	07:52:09.128	trace	yii\web\Application::handleRequest	Route requested: 'user/login'
	07:52:09.128	trace	yii\base\Module::getModule	Loading module: user
	07:52:09.130	trace	yii\base\Controller::runAction	Route to run: user/default/login
	07:52:09.132	info	yii\web\Session::open	Session started
	07:52:09.142	info	yii\db\Command::query	SELECT * FROM `user` WHERE (`id`=1) AND (`status`=10)
		/WebDev/User/example.com/yii-application/common/models/User.php (63)
	07:52:09.142	info	yii\db\Connection::open	Opening DB connection: mysql:host=localhost;dbname=example_db
		/WebDev/User/example.com/yii-application/common/models/User.php (63)
	07:52:09.144	info	yii\db\Command::query	SELECT * FROM `user` WHERE (`id`=1) AND (`status`=10)
		/WebDev/User/example.com/yii-application/common/models/User.php (63)
	07:52:09.145	trace	yii\base\InlineAction::runWithParams	Running action: amnah\yii2\user\controllers\DefaultController::actionLogin()

**Comment by amnah** [comment]
Can you post your config/web.php file pls? (make sure you remove important credentials)

**Comment by Draven714** [comment]
I used the Yii2 Advanced. Here is my common/config/main-local.php:

	<?php
	return [
		'components' => [
			'db' => [
				'class' => 'yii\db\Connection',
				'dsn' => 'mysql:host=localhost;dbname=example_db',
				'username' => 'example_user',
				'password' => 'example_password',
				'charset' => 'utf8',
			],
			'mailer' => [
				'class' => 'yii\swiftmailer\Mailer',
				'viewPath' => '@common/mail',
				// send all mails to a file by default. You have to set
				// 'useFileTransport' to false and configure a transport
				// for the mailer to send real emails.
				'useFileTransport' => true,
				'messageConfig' => [
					'from' => ['admin@website.com' => 'Admin'], // this is needed for sending emails
					'charset' => 'UTF-8',
				],
			],
		   'user' => [
				'class' => 'amnah\yii2\user\components\User',
			],
		],
		'modules' => [
			'user' => [
				'class' => 'amnah\yii2\user\Module',
				// set custom module properties here ...
			],
		],
	];

**Comment by amnah** [comment]
Hmmm I forget the reason why, but the advanced app requires special configuration. Can you try this?

```php
'components' => [
        // NOTE: in the yii2-advanced-app, the user component should be updated in
        // 'frontend/config/main.php' and/or 'backend/config/main.php' (OR you can add it
        // to 'common/config' if you remove it from frontend/backend)
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],
        ....
]
```

**Comment by Draven714** [comment]
Sorry, but that is exactly what I have already... Or am I missing something?

**Comment by Draven714** [comment]
Nevermind, figured it out. in frontend/config/main.php I had to remove the 'indentityClass'  param.

	<?php
	$params = array_merge(
		require(__DIR__ . '/../../common/config/params.php'),
		require(__DIR__ . '/../../common/config/params-local.php'),
		require(__DIR__ . '/params.php'),
		require(__DIR__ . '/params-local.php')
	);

	return [
		'id' => 'app-frontend',
		'basePath' => dirname(__DIR__),
		'bootstrap' => ['log'],
		'controllerNamespace' => 'frontend\controllers',
		'components' => [
			'user' => [
				'identityClass' => 'common\models\User',
			],
			'log' => [
				'traceLevel' => YII_DEBUG ? 3 : 0,
				'targets' => [
					[
						'class' => 'yii\log\FileTarget',
						'levels' => ['error', 'warning'],
					],
				],
			],
			'errorHandler' => [
				'errorAction' => 'site/error',
			],
			/*
			'view' => [
				'theme' => [
					'pathMap' => ['@app/views' => 'themes/defaultbv'],
					'baseUrl'   => 'themes/default'
				],
			],
			*/
		],
		//'defaultRoute' => 'user/login',
		'params' => $params,
	];
