### ISSUE TITLE
Switch identity

### ISSUE THREAD

**Issue by packcode** [amnah/yii2-user#70]
Is there a way to switch the identity of a user.e. g. if i am logged in as "admin" can i switch to one of the user's identity from my user class.
pl. help me out

**Comment by amnah** [comment]
Something like this?

```php
$user = User::findOne($id);
$duration = 0;
Yii::$app->user->login($user, $duration);
```

**Comment by packcode** [comment]
Thank you this worked like a charm...!!

**Comment by alexander-suter** [comment]
Better us switchIdentity in \yii\web\User
