### ISSUE TITLE
Yii2 Advanced Setup - Backend Login Bad Request (#400) - Unable to verify your data submission. 

### ISSUE THREAD

**Issue by cicsolutions** [amnah/yii2-user#73]
First I must say how much I appreciate your User Extension.  It's really a wonderful extension and will be at the core of all my projects.

I'm setting up the Amnah User Extension for a Yii2 Advanced app, and everything works great if I treat my frontend and backend as different apps and use different subdomains for each app.  For example, I have front.myapp.loc and back.myapp.loc, and I am able to log into the front and back end through the Amnah User login page successfully.

I would like to use the same domain name for our entire solution, so I've been using some Apache rewrites to accomplish accessing the backend site from myapp.loc/admin, and just accessing the frontend from myapp.loc.  I'm using the following tutorial to accomplish this setup: http://aaronfrancis.com/blog/2014/1/9/hosting-an-advanced-yii2-application-on-heroku

When I'm using Aaron's Request.php component, I am still able to login via the Amnah User extension on the frontend, but not on the backend.  On the backend, I receive a "Bad Request (#400) - Unable to verify your data submission" error message.

It's odd because I've accomplished this setup for another project, but it's a much older version of Yii and Amnah User Module (i.e. I haven't updated the composer dependencies in many months).  I wonder if something new is affecting this?

Any ideas or suggestions you can offer are greatly appreciated.  And thank you for all you do to support our community!

Best regards,

Caleb

**Comment by amnah** [comment]
Hmm, it looks like that has to do with [csrf](http://stackoverflow.com/questions/26459419/why-get-unable-to-verify-your-data-submission-error-in-yii2). 

From what I understand, the backend and frontend should probably have different csrf keys. But if you put them both on the same domain, you may need to make them have the same key instead.

So check the ```main-local.php``` files and try setting them to the same value - see if that works.

**Comment by cicsolutions** [comment]
You're a Genius!  That was it!  Thank you so much!

**Comment by supergiok** [comment]
Thank you! You saved... my night!
