### ISSUE TITLE
Demo is not working as password is wrong

### ISSUE THREAD

**Issue by gb5256** [amnah/yii2-user#75]
It looks like you demo site is not working.
As the demo site does allow people to change the password, somebody obviously did.
Which makes the demo now not useable.

**Comment by amnah** [comment]
Fixed, neo/neo should work now.

**Comment by gb5256** [comment]
As you allow users to change the password ... Guess what? The password neo is not working anymore.
So this is the second time that I try to test your demo, but can't.
This is keeping users away from using you code (like me).
