### ISSUE TITLE
View files not found

### ISSUE THREAD

**Issue by vsmelarkod** [amnah/yii2-user#77]
Hi, I followed the installation according to the instructions and was successful in 1) installing Yii via composer 2) installing yii2-user via composer 3) edit config/web and config/db to connect to a local database and 4) successfully apply migrations (can see the database tables created). But, when I go to localhost/basic/web/user, the browser shows a Not Found error. Is there a step I am missing? thank you for your help. My config file is pasted below - 

$params = require(__DIR__ . '/params.php');

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
	'modules' => [
        'user' => [
            'class' => 'amnah\yii2\user\Module',
            // set custom module properties here ...
        ],
    ],
    'components' => [
        'request' => [
            'cookieValidationKey' => 'abracadabra',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'user' => [
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
			'class' => 'amnah\yii2\user\components\User',
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => true,
			'messageConfig' => [
                'from' => ['admin@website.com' => 'Admin'], // this is needed for sending emails
                'charset' => 'UTF-8',
            ]
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => require(__DIR__ . '/db.php'),
    ],
    'params' => $params,
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = 'yii\debug\Module';

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = 'yii\gii\Module';
}

return $config;

**Comment by amnah** [comment]
Hmm seems like everything should be working. Can you paste the exact error message?

**Comment by amnah** [comment]
Oh, you didn't set up clean urls? Try this out:

http://stackoverflow.com/questions/26525320/enable-clean-url-in-yii2

**Comment by vsmelarkod** [comment]
Yes sir.. That worked and looks great! thanks.
