### ISSUE TITLE
Curious about Upcoming Features

### ISSUE THREAD

**Issue by cicsolutions** [amnah/yii2-user#78]
Hello and thank you for such an amazing Yii2 extension!  I'm curious if you've considered or intend to include the following features:

1) Confirm Email Field - this would be a second email field on the registration form that would require the user to enter their email address twice, with the second text input validating that the email addresses match.  This is just a nice-to-have feature to ensure the user has entered the proper email address with no typos.

2) Confirm Password Field - this is a similar feature to #1 above.  This is less important because if the user has a typo in the password, they can always use the password reset feature.  But it would be a nice to have option.

Thanks so much for everything!

Best regards,

Caleb

**Comment by amnah** [comment]
Sorry, but I don't intend to include those because I don't like adding extra fields in. 

If you want to add it in yourself, it's very easy. Just take a look at the User model and check out ```$newPasswordConfirm```.
