### ISSUE TITLE
Authentication failed in IE11 with the error "Bad Request (#400) - Unable to verify yor data submission"

### ISSUE THREAD

**Issue by ajaryba** [amnah/yii2-user#80]
Hello, 
I have the "Bad Request (#400)" error in IE11 trying to login with neo/neo. At the same time authentication process in Chrome and Opera works fine. I've tried to switch csrf by setting 'enableCsrfValidation' to false in which case the error message vanishes, but the user still can't login. Could you please suggest any solution how to fix that?
Thank you in advance,
Roman

**Comment by amnah** [comment]
this maybe?

http://answers.microsoft.com/en-us/ie/forum/ie11-windows_7/ie11-returns-http-400-bad-request-error/a9e07a98-5d26-41ab-ac32-d6a66571d691
