### ISSUE TITLE
Call to undefined method amnah\yii2\user\components\User::findIdentity()

### ISSUE THREAD

**Issue by ajkosh** [amnah/yii2-user#81]
in basic app i m getting this after install

**Comment by amnah** [comment]
What's your config?

**Comment by ajkosh** [comment]
this is my confgi file
<?php

$params = require(__DIR__ . '/params.php');

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'modules' => [
        'user' => [
            'class' => 'amnah\yii2\user\Module',
            // set custom module properties here ...
        ],
    ],
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'KAizUcc7tjKN0LAK_nSxn7cmd5anjbs2',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        // 'user' => [
        //     'identityClass' => 'app\models\User',
        //     'enableAutoLogin' => false,
        // ],
        'user' => [
            'identityClass' => 'amnah\yii2\user\components\User',
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        // 'mailer' => [
        //     'class' => 'yii\swiftmailer\Mailer',
        //     // send all mails to a file by default. You have to set
        //     // 'useFileTransport' to false and configure a transport
        //     // for the mailer to send real emails.
        //     'useFileTransport' => true,
        // ],
          'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => true,
            'messageConfig' => [
                'from' => ['admin@website.com' => 'Admin'], // this is needed for sending emails
                'charset' => 'UTF-8',
            ]
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => require(__DIR__ . '/db.php'),
        //   'urlManager' => [
        //     'enablePrettyUrl' => true,
        //     'showScriptName' => false,
        // ],
    ],

    'params' => $params,
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    //$config['bootstrap'][] = 'debug';
    //$config['modules']['debug'] = 'yii\debug\Module';

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = 'yii\gii\Module';
}

return $config;

**Comment by ajkosh** [comment]
thnku for ur reply plz if u can help ,i need this.

**Comment by amnah** [comment]
Ahh, I see. Try this:

```php
'user' => [
    'identityClass' => 'amnah\yii2\user\components\User',
],
```

should be

```php
'user' => [
    'class' => 'amnah\yii2\user\components\User',
],
```

**Comment by ajkosh** [comment]
ok i try this

**Comment by ajkosh** [comment]
this error is coming 
Calling unknown method: app\models\User::updateLoginMeta()

**Comment by ajkosh** [comment]
in login page facebook auth is not showing

**Comment by amnah** [comment]
what version do you have installed? you can check by going to /user

**Comment by ajkosh** [comment]
it is latest version but i checked in firebug 
i have missed authchoice.css and authchoice.js files
how to get those files

**Comment by amnah** [comment]
hmm how did you install the module? if you installed it via composer it
should've installed yii2-authclient as well

at this point maybe you should try a fresh installation, something messed
up...

**Comment by ajkosh** [comment]
i installed from composer
thnku i try again ,but can u tell me i m using yii2 admin

**Comment by amnah** [comment]
Sorry but I've never used that module. You'll have to ask them for help

**Comment by ajkosh** [comment]
can u tell me how ur confirm is working,i mean how you call action call confirm from email confirmation link.

**Comment by amnah** [comment]
I'm not sure what you mean... It just calls the [action in the controller](https://github.com/amnah/yii2-user/blob/master/controllers/DefaultController.php#L193)

**Comment by ajkosh** [comment]
how this action you are calling,from where it is calling,that i want to know ?

**Comment by amnah** [comment]
Where the link is generated? [Here](https://github.com/amnah/yii2-user/blob/master/mail/confirmEmail.php#L17)
