### ISSUE TITLE
Conformation email is not get

### ISSUE THREAD

**Issue by sks1990** [amnah/yii2-user#82]
Hello sir,
I have new developer in yii2,I have integrate amnah/Yii2-user module,it is running successfully,but email conformation is not sent whiten user Registration time, and I am working on localhost( wamp server).

message=>Successfully registered [ singh.sandeep1990@gmail.com ] - Please check your email to confirm your account

**Comment by amnah** [comment]
did you set up your email config properly? by default "useFileTransport" is
true, which means it writes it to a file

**Comment by PaoloVIP** [comment]
Maybe my problem is different:
on my local site I can send mail without problem for user login confermation, using user amnah module ( https://github.com/amnah/yii2-user ).
On the real site I can't. Same configuration. Any idea?

This my web.cfg (working on local site)

---
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'transport' => [
            	'class' => 'Swift_SmtpTransport',
            	'host' => 'expandev.com',
            	'username' => 'mymail@expandev.com',
            	'password' => 'pwd',
            	'port' => '25',
            	'encryption' => 'tls',
                ],
        ],
      'mail' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'messageConfig' => [
                'from' => ['mymail@expandev.com' => 'Admin'], // this is needed for sending emails
                'charset' => 'UTF-8',
        ],

---

This is the error:

Swift_TransportException
Connection could not be established with host expandev.com [Connection timed out #110]

    1. in /home/maldistrjr/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php at line 265
    256257258259260261262263264265266267268269270271272273274

            if (!empty($this->_params['timeout'])) {
                $timeout = $this->_params['timeout'];
            }
            $options = array();
            if (!empty($this->_params['sourceIp'])) {
                $options['socket']['bindto'] = $this->_params['sourceIp'].':0';
            }
            $this->_stream = @stream_socket_client($host.':'.$this->_params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, stream_context_create($options));
            if (false === $this->_stream) {
                throw new Swift_TransportException(
                    'Connection could not be established with host '.$this->_params['host'].
                    ' ['.$errstr.' #'.$errno.']'
                    );
            }
            if (!empty($this->_params['blocking'])) {
                stream_set_blocking($this->_stream, 1);
            } else {
                stream_set_blocking($this->_stream, 0);
            }

    2. in /home/maldistrjr/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php – Swift_Transport_StreamBuffer::_establishSocketConnection() at line 62
    56575859606162636465666768

            switch ($params['type']) {
                case self::TYPE_PROCESS:
                    $this->_establishProcessConnection();
                    break;
                case self::TYPE_SOCKET:
                default:
                    $this->_establishSocketConnection();
                    break;
            }
        }
     
        /**
         * Set an individual param on the buffer (e.g. switching to SSL).

    3. in /home/maldistrjr/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php – Swift_Transport_StreamBuffer::initialize(['protocol' => 'tcp', 'host' => 'expandev.com', 'port' => 25, 'timeout' => 30, ...]) at line 113
    107108109110111112113114115116117118119

                    if ($evt->bubbleCancelled()) {
                        return;
                    }
                }
     
                try {
                    $this->_buffer->initialize($this->_getBufferParams());
                } catch (Swift_TransportException $e) {
                    $this->_throwException($e);
                }
                $this->_readGreeting();
                $this->_doHeloCommand();
     

    4. in /home/maldistrjr/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php – Swift_Transport_AbstractSmtpTransport::start() at line 79
    73747576777879808182838485

         */
        public function send(Swift_Mime_Message $message, &$failedRecipients = null)
        {
            $failedRecipients = (array) $failedRecipients;
     
            if (!$this->_transport->isStarted()) {
                $this->_transport->start();
            }
     
            $sent = 0;
     
            try {
                $sent = $this->_transport->send($message, $failedRecipients);

    5. in /home/maldistrjr/vendor/yiisoft/yii2-swiftmailer/Mailer.php – Swift_Mailer::send(Swift_Message) at line 140
    134135136137138139140141142143144145146

            $address = $message->getTo();
            if (is_array($address)) {
                $address = implode(', ', array_keys($address));
            }
            Yii::info('Sending email "' . $message->getSubject() . '" to "' . $address . '"', __METHOD__);
     
            return $this->getSwiftMailer()->send($message->getSwiftMessage()) > 0;
        }
     
        /**
         * Creates Swift mailer instance.
         * @return \Swift_Mailer mailer instance.
         */

    6. in /home/maldistrjr/vendor/yiisoft/yii2/mail/BaseMailer.php – yii\swiftmailer\Mailer::sendMessage(yii\swiftmailer\Message) at line 260
    7. in /home/maldistrjr/vendor/yiisoft/yii2/mail/BaseMessage.php – yii\mail\BaseMailer::send(yii\swiftmailer\Message) at line 48
    8. in /home/maldistrjr/vendor/amnah/yii2-user/models/User.php – yii\mail\BaseMessage::send() at line 489
    483484485486487488489490491492493494495

                ->setSubject($subject);
     
            // check for messageConfig before sending (for backwards-compatible purposes)
            if (empty($mailer->messageConfig["from"])) {
                $message->setFrom(Yii::$app->params["adminEmail"]);
            }
            $result = $message->send();
     
            // restore view path and return result
            $mailer->viewPath = $oldViewPath;
            return $result;
        }
     

    9. in /home/maldistrjr/vendor/amnah/yii2-user/controllers/DefaultController.php – amnah\yii2\user\models\User::sendEmailConfirmation(amnah\yii2\user\models\UserKey) at line 180
    174175176177178179180181182183184185186

     
            // check if we have a userKey type to process, or just log user in directly
            if ($userKeyType) {
     
                // generate userKey and send email
                $userKey = $userKey::generate($user->id, $userKeyType);
                if (!$numSent = $user->sendEmailConfirmation($userKey)) {
     
                    // handle email error
                    //Yii::$app->session->setFlash("Email-error", "Failed to send email");
                }
            } else {
                Yii::$app->user->login($user, Yii::$app->getModule("user")->loginDuration);

    10. in /home/maldistrjr/vendor/amnah/yii2-user/controllers/DefaultController.php – amnah\yii2\user\controllers\DefaultController::afterRegister(amnah\yii2\user\models\User) at line 136
    130131132133134135136137138139140141142

                if ($user->validate() && $profile->validate()) {
     
                    // perform registration
                    $role = Yii::$app->getModule("user")->model("Role");
                    $user->setRegisterAttributes($role::ROLE_USER, Yii::$app->request->userIP)->save(false);
                    $profile->setUser($user->id)->save(false);
                    $this->afterRegister($user);
     
                    // set flash
                    // don't use $this->refresh() because user may automatically be logged in and get 403 forbidden
                    $successText = Yii::t("user", "Successfully registered [ {displayName} ]", ["displayName" => $user->getDisplayName()]);
                    $guestText = "";
                    if (Yii::$app->user->isGuest) {

    11. amnah\yii2\user\controllers\DefaultController::actionRegister()
    12. in /home/maldistrjr/vendor/yiisoft/yii2/base/InlineAction.php – call_user_func_array([amnah\yii2\user\controllers\DefaultController, 'actionRegister'], []) at line 55
    13. in /home/maldistrjr/vendor/yiisoft/yii2/base/Controller.php – yii\base\InlineAction::runWithParams([]) at line 151
    14. in /home/maldistrjr/vendor/yiisoft/yii2/base/Module.php – yii\base\Controller::runAction('register', []) at line 455
    15. in /home/maldistrjr/vendor/yiisoft/yii2/web/Application.php – yii\base\Module::runAction('user/register', []) at line 83
    16. in /home/maldistrjr/vendor/yiisoft/yii2/base/Application.php – yii\web\Application::handleRequest(yii\web\Request) at line 375
    17. in /home/maldistrjr/www/index.php – yii\base\Application::run() at line 12
    6789101112

     
    require(__DIR__ . '/../vendor/autoload.php');
    require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
     
    $config = require(__DIR__ . '/../config/web.php');
     
    (new yii\web\Application($config))->run();

$_POST = [
    '_csrf' => 'bUdpeC1PY2I0C0QifjoaLQYJOjlPHDQXWnMFLGx5JgBddioCYyYtGg==',
    'User' => [
        'email' => 'paolo@visnoviz.org',
        'newPassword' => 'george',
    ],
];

$_SERVER = [
    'USER' => 'maldistrjr',
    'FCGI_ROLE' => 'RESPONDER',
    'REDIRECT_STATUS' => '200',
    'UNIQUE_ID' => 'VSPtwAoARiwAABuj5isAAAB0',
    'GEOIP_COUNTRY_CODE' => 'IT',
    'GEOIP_COUNTRY_NAME' => 'Italy',
    'GEOIP_REGION' => '06',
    'GEOIP_CITY' => 'Trieste',
    'GEOIP_DMA_CODE' => '0',
    'GEOIP_AREA_CODE' => '0',
    'GEOIP_LATITUDE' => '45.633301',
    'GEOIP_LONGITUDE' => '13.816700',
    'SCRIPT_URL' => '/user/register',
    'SCRIPT_URI' => 'http://www.maldistrada.it/user/register',
    'CFG_CLUSTER' => 'cluster011',
    'ENVIRONMENT' => 'production',
    'PHP_VER' => '5_3',
    'REGISTER_GLOBALS' => '0',
    'HTTP_REMOTE_IP' => '87.15.181.235',
    'HTTP_HOST' => 'www.maldistrada.it',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'HTTP_ACCEPT_LANGUAGE' => 'it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
    'HTTP_REFERER' => 'http://www.maldistrada.it/user/register',
    'HTTP_COOKIE' => '_ga=GA1.2.2004730633.1424975170; 300gp=R3395948797; _csrf=0cce02d350ec9fff99c282ca342310c0d45e6a0f4d302bd8b901ece4860174fda%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22YL-ZSuyOkNSAbSWu74lTA6Eb01CzNiNx%22%3B%7D; PHPSESSID=64ab5f8f2b09995224a57820717b9a1c; _gat=1',
    'HTTP_CONNECTION' => 'keep-alive',
    'CONTENT_TYPE' => 'application/x-www-form-urlencoded',
    'CONTENT_LENGTH' => '132',
    'SERVER_SIGNATURE' => '',
    'SERVER_SOFTWARE' => 'Apache',
    'SERVER_NAME' => 'www.maldistrada.it',
    'SERVER_ADDR' => '178.33.103.104',
    'SERVER_PORT' => '80',
    'REMOTE_ADDR' => '87.15.181.235',
    'DOCUMENT_ROOT' => '/home/maldistrjr/www',
    'SERVER_ADMIN' => 'postmaster@www.maldistrada.it',
    'SCRIPT_FILENAME' => '/home/maldistrjr/www/index.php',
    'REMOTE_PORT' => '23213',
    'REDIRECT_URL' => '/user/register',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'REQUEST_METHOD' => 'POST',
    'QUERY_STRING' => '',
    'REQUEST_URI' => '/user/register',
    'SCRIPT_NAME' => '/index.php',
    'PHP_SELF' => '/index.php',
    'REQUEST_TIME_FLOAT' => 1428417984.7092061,
    'REQUEST_TIME' => 1428417984,
    'argv' => [],
    'argc' => 0,
];

$_COOKIE = [
    '_ga' => 'GA1.2.2004730633.1424975170',
    '300gp' => 'R3395948797',
    '_csrf' => '0cce02d350ec9fff99c282ca342310c0d45e6a0f4d302bd8b901ece4860174fda:2:{i:0;s:5:"_csrf";i:1;s:32:"YL-ZSuyOkNSAbSWu74lTA6Eb01CzNiNx";}',
    'PHPSESSID' => '64ab5f8f2b09995224a57820717b9a1c',
    '_gat' => '1',
];

$_SESSION = [
    '__flash' => [],
];

$_ENV = [
    'USER' => 'maldistrjr',
    'FCGI_ROLE' => 'RESPONDER',
    'REDIRECT_STATUS' => '200',
    'UNIQUE_ID' => 'VSPtwAoARiwAABuj5isAAAB0',
    'GEOIP_COUNTRY_CODE' => 'IT',
    'GEOIP_COUNTRY_NAME' => 'Italy',
    'GEOIP_REGION' => '06',
    'GEOIP_CITY' => 'Trieste',
    'GEOIP_DMA_CODE' => '0',
    'GEOIP_AREA_CODE' => '0',
    'GEOIP_LATITUDE' => '45.633301',
    'GEOIP_LONGITUDE' => '13.816700',
    'SCRIPT_URL' => '/user/register',
    'SCRIPT_URI' => 'http://www.maldistrada.it/user/register',
    'CFG_CLUSTER' => 'cluster011',
    'ENVIRONMENT' => 'production',
    'PHP_VER' => '5_3',
    'REGISTER_GLOBALS' => '0',
    'HTTP_REMOTE_IP' => '87.15.181.235',
    'HTTP_HOST' => 'www.maldistrada.it',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'HTTP_ACCEPT_LANGUAGE' => 'it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
    'HTTP_REFERER' => 'http://www.maldistrada.it/user/register',
    'HTTP_COOKIE' => '_ga=GA1.2.2004730633.1424975170; 300gp=R3395948797; _csrf=0cce02d350ec9fff99c282ca342310c0d45e6a0f4d302bd8b901ece4860174fda%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22YL-ZSuyOkNSAbSWu74lTA6Eb01CzNiNx%22%3B%7D; PHPSESSID=64ab5f8f2b09995224a57820717b9a1c; _gat=1',
    'HTTP_CONNECTION' => 'keep-alive',
    'CONTENT_TYPE' => 'application/x-www-form-urlencoded',
    'CONTENT_LENGTH' => '132',
    'SERVER_SIGNATURE' => '',
    'SERVER_SOFTWARE' => 'Apache',
    'SERVER_NAME' => 'www.maldistrada.it',
    'SERVER_ADDR' => '178.33.103.104',
    'SERVER_PORT' => '80',
    'REMOTE_ADDR' => '87.15.181.235',
    'DOCUMENT_ROOT' => '/home/maldistrjr/www',
    'SERVER_ADMIN' => 'postmaster@www.maldistrada.it',
    'SCRIPT_FILENAME' => '/home/maldistrjr/www/index.php',
    'REMOTE_PORT' => '23213',
    'REDIRECT_URL' => '/user/register',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'REQUEST_METHOD' => 'POST',
    'QUERY_STRING' => '',
    'REQUEST_URI' => '/user/register',
    'SCRIPT_NAME' => '/index.php',
    'PHP_SELF' => '/index.php',
    'REQUEST_TIME_FLOAT' => 1428417984.7092061,
    'REQUEST_TIME' => 1428417984,
    'argv' => [],
    'argc' => 0,
];

Yii Framework

2015-04-07, 16:46:55

Apache

Yii Framework/2.0.3

**Comment by amnah** [comment]
looks like a configuration issue ... the swiftmailer can't connect to your
mail host. are you sure the credentials are correct?

also you shouldn't have both "mailer" and "mail" components - should just
be "mailer"

**Comment by PaoloVIP** [comment]
Yas, I'm sure. The same configuration works fine on local development site. And real site and development one are the same! Any idea?

(Please, can you delete mail and password from previous messages? )

**Comment by amnah** [comment]
sounds like your live server is preventing the email from connecting, maybe try asking them for email setup instructions

**Comment by PaoloVIP** [comment]
Yes, I think the same. Some provider restriction. I changed my web.cfg, but nothing changed. Is this correct now?

        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
	    'useFileTransport' => false,
            'transport' => [
            	'class' => 'Swift_SmtpTransport',
            	'host' => 'expandev.com',
            	'username' => 'mymail@expandev.com',
            	'password' => 'mypass',
            	'port' => '25',
            	'encryption' => 'tls',
                ],
            'messageConfig' => [
                'from' => ['mymail@expandev.com' => 'Admin'], // this is needed for sending emails
                'charset' => 'UTF-8',
            ],

**Comment by amnah** [comment]
yep, that's correct

let me know if you figure out what's wrong with the email provider

**Comment by PaoloVIP** [comment]
Solved. It was a trivial smtp port problem. My provider changed it, but without telling it to anyone.
You are always very kind. Thank you.

**Comment by sks1990** [comment]
Hello Dear sir,
I am using the following code.
I have changed "useFileTransport" value `true/false` both ,but not sent the  email.

 'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => true,
            'messageConfig' => [
                'from' => ['singh.sandeep1990@gmail.com' => 'Admin'], // this is needed for sending emails
                'charset' => 'UTF-8',
            ]
        ],


Thanks.

**Comment by amnah** [comment]
What are you using to send emails? This part:

```php
'transport' => [
            'class' => 'Swift_SmtpTransport',
            'host' => 'xxxxxxx.com',
            'username' => 'yyyyyyyy',
            'password' => 'zzzzzz',
            'port' => '25',
            'encryption' => 'tls',
            ],
```

If you're using the defaults from WAMP server it probably won't work. Set up a free account at mailgun or sendgrid or something and use that instead.

**Comment by sks1990** [comment]
Hello sir,
I am nothing using for Third party API.Why using API?

I have required,If user register then sent the email verification link.

thanks.
