### ISSUE TITLE
yii2-user + sql server

### ISSUE THREAD

**Issue by pafcosta** [amnah/yii2-user#83]
I installed the extension with sql server. It created the database structure.
When I tried to login the first time (neo\neo), I didn't got any error, but i continue always with guest user. I debug e note the Yii::$app->getModule("user")->loginRedirect is empty. 

Can you help me please.

**Comment by amnah** [comment]
Usually, that's an issue with the config. Did you set your user component properly?

If you want, you can just paste your config file here
