### ISSUE TITLE
Add a role

### ISSUE THREAD

**Issue by PaoloVIP** [amnah/yii2-user#88]
Hello, in your guide I read "Add more database columns for permissions as needed.", and I do it adding one more role: sysadmin, with can_sysadmin and index 3 (1 is admin, 2 is normal user).

I can see in user administration the new role, but I can't change it. I can select the new role, but it will not saved at all. What I can forgot to change, please?

Edit: Sysadmin also include admin role. In role table user is set to 0 for can_admin and can_sysadmin, admin is set to 1 for can_admin and 0 for can_sysadmin, sysadmin was setting 1 for both can_admin and can_sysadmin.

Edit 2: Bring again to original configuration, but now I noticed that not only the role don't change (it not saved to db), but also the user status too. Maybe I should do an update to the db after the last version installed ?

Edit 3: All ok, in _form view I disabled in wrong way <?= $form->field($profile, 'full_name'); ?>, so nothing was saved.  :-) Thank you

**Comment by amnah** [comment]
You'll need to [extend](https://github.com/amnah/yii2-user#how-do-i-extend-this-package) the ```Role``` model and override the [rules](https://github.com/amnah/yii2-user/blob/master/models/Role.php#L42) function.

Good point though, I'll update this to make it dynamic

**Comment by PaoloVIP** [comment]
I only added the column in db and, after correcting my mistakes, it works fine. The sysadmin can do all what admin can, plus what sysadmin can: Yii::$app->user->can("sysadmin")).

**Comment by halk2269** [comment]
Hello. I want to add my 2 role in the program (moderator and reader). Pleas tell me what I should do. I added 2 lines in the table "role" . What do I do next, if you can incrementally . And as I close access to a separate link or page. thank you
