### ISSUE TITLE
Get value instead Id in DetailView

### ISSUE THREAD

**Issue by PaoloVIP** [amnah/yii2-user#91]
Sorry if I bored you again asking trivial things, but I do not find a solution.
Is there a way to get "role name" instead of "role id" in DetailView of view/admin/view.php ?

**Comment by amnah** [comment]
```php
 ['label' => 'Role', 'value' => $user->role->name,],
```

http://www.yiiframework.com/doc-2.0/yii-widgets-detailview.html

**Comment by PaoloVIP** [comment]
Ah, ok. Simple. Thank you.
