### ISSUE TITLE
Yii2 Basic, login page "404 not found"

### ISSUE THREAD

**Issue by terrytao** [amnah/yii2-user#92]
I've use the Yii2 Basic, 1) project setup ok, got the "congratulations " homepage ok, 2)using composer downloaded "amnah" ok, leave it in the "vendor" directory, didn't change anything, 3) run migration ok, all 5 tables created in the database , 4)made changes on the app/config/web.php according to the Readme file, 4)made change on layout/main according to the Readme file.

When click "User" on the home page, it brings me a list of URLs, but when click any link in the list, or the "login" link on the top right corner, it says "Page Not Found, #404",  no compiling error though,  below is the config and layouts/main, 

Can someone help? Thank you very much!

=====web config==
<?php

$params = require(__DIR__ . '/params.php');

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log',
        function () { return Yii::$app->getModule("user"); },
        ],
   
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'wqRLjPNF3XxcM-lwaEN3d1_n3j24cQ1m',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        
        'user' => [
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
        ],
       
        'class' => 'auth\components\User',
       
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        
         'user' => [
             'class' => 'amnah\yii2\user\components\User',
        ],
        
        
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => true,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => require(__DIR__ . '/db.php'),
    ],
      'modules' => [
        'user' => [
            'class' => 'amnah\yii2\user\Module',
            // set custom module properties here ...
        ],
    ],
    
    'params' => $params,
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = 'yii\debug\Module';

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = 'yii\gii\Module';
}

return $config;

====layouts/main ====

  <?php
            NavBar::begin([
                'brandLabel' => 'My Company',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                      ['label' => 'Home', 'url' => ['/site/index']],
                      ['label' => 'About', 'url' => ['/site/about']],
                      ['label' => 'Contact', 'url' => ['/site/contact']],
                      ['label' => 'User', 'url' => ['/user']],
                     Yii::$app->user->isGuest ?
                       ['label' => 'Login', 'url' => ['/user/login']] :
                       ['label' => 'Logout (' . Yii::$app->user->displayName . ')',
                        'url' => ['/user/logout'],
                        'linkOptions' => ['data-method' => 'post']],
                ],
            ]);
            NavBar::end();
        ?>

======

**Comment by PaoloVIP** [comment]
I think you miss to introduce in your web.php:

// app/config/web.php
return [
    'bootstrap' => [
        'log',
        function () { return Yii::$app->getModule("user"); }, // to set up /user routes
    ],
    ...
]

Look at https://github.com/amnah/yii2-user/blob/master/UPGRADE.md

**Comment by vicmonmena** [comment]
Hi!

I'm getting the same issue:when I finish to config the project according to Readme and I go to login:

http://localhost/basic/web/index.php?r=user%2Flogin -> Not Found (#404)
http://localhost/basic/web/user/login -> 404 Not found

Just http://localhost/basic/web/index.php?r=user shows the Actions list but any links works.

This is my app/config.web.php file:

```
<?php

$params = require(__DIR__ . '/params.php');

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => [
		'log',
		function () { return Yii::$app->getModule("user"); }, // to set up /user routes
	],
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'loFd6cmuX5ixW7RfsUxp8V8SENIw33Oo',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => true,
            'messageConfig' => [
                'from' => ['admin@website.com' => 'Admin'], // this is needed for sending emails
                'charset' => 'UTF-8',
            ]
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => require(__DIR__ . '/db.php'),
    ],
	'modules' => [
        'user' => [
            'class' => 'amnah\yii2\user\Module',
            // set custom module properties here ...
        ],
    ],
    'params' => $params,
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = 'yii\debug\Module';

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = 'yii\gii\Module';
}

return $config;
```

I'm working with Yii , basic template and empty project.

**Comment by amnah** [comment]
hmm... what version do you have installed? it says it on the
http://localhost/basic/web/index.php?r=user page

**Comment by amnah** [comment]
Ahhhhhhhhhhhh ok, I think i've figured it out. 

The short answer is: [enable pretty urls](http://stackoverflow.com/questions/26525320/enable-clean-url-in-yii2). Unless for some specific reason you can't, this will solve the issue.

The long answer is: the [Module::bootstrap()](https://github.com/amnah/yii2-user/blob/master/Module.php#L142) is doing nothing because [enablePrettyUrl is disabled](http://www.yiiframework.com/doc-2.0/yii-web-urlmanager.html#addRules()-detail). In that case you'd need to actually to go to ```http://localhost/basic/web/index.php?r=user/default/login```

Hmmm... need to think about this a bit. I don't like the [old hack](https://github.com/amnah/yii2-user/blob/7b2b2ef9547b9f2d8930f826fb90816c1c2d913c/Module.php#L262) I used but I may not have a choice...

**Comment by vicmonmena** [comment]
Thank you so much!

At this moment the state is:

Going to: http://localhost/basic/web/index.php?r=user/default/login -> it shows me login page correctly.

If I set my configuration according to [enable pretty urls](http://stackoverflow.com/questions/26525320/enable-clean-url-in-yii2) every url give me:

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.9 (Win32) PHP/5.5.12 Server at localhost Port 80
```

**Comment by amnah** [comment]
Do you have [mod_rewrite](http://stackoverflow.com/a/12429052) enabled?

**Comment by terrytao** [comment]
Problem Solved! I just added this to the app\config\web.php, all links now worked, I didn't touch any httpd.conf

 'urlManager' => [
        'enablePrettyUrl' => true,
    
    ],

Before that , I tried 1) if I go to http://blog/web/index.php?r=user/default/register, it worked, 2) I actually tried put enable pretty urls with more options which I don't remember now, same happened as  vicmonmena , now I just put a single line  'enablePrettyUrl' => true, no other options, it worked, don't know why. So far so good, thanks everyone!

**Comment by terrytao** [comment]
Problem solved, thank you so much Amnah for your help, you're great, you actually mentioned the pretty url thing in the previous email, that was indeed the issue, at least for me. I left the details at github.
Terry

**Comment by terrytao** [comment]
Problem Solved! I just added this to the app\config\web.php, all links now worked, I didn't touch any httpd.conf

 'urlManager' => [
        'enablePrettyUrl' => true,
    
    ],

Before that , I tried 1) if I go to http://blog/web/index.php?r=user/default/register, it worked, 2) I actually tried put enable pretty urls with more options which I don't remember now, same happened as  vicmonmena , now I just put a single line  'enablePrettyUrl' => true, no other options, it worked, don't know why. So far so good, thanks everyone!

**Comment by vicmonmena** [comment]
I've tried both things:

Enable mod_rewrite and just set:

```
'urlManager' => [
		'enablePrettyUrl' => true,
	],
```
in app/config/web.php and nothing works for me :_(

When I've done the same as terrytao, http://localhost/basic/web/ give me:

```
Invalid Call – yii\base\InvalidCallException

Setting read-only property: yii\web\Application::urlManager
```

**Comment by amnah** [comment]
Did you restart apache after enabling mod_rewrite? Did you hide the script name?

```php
'urlManager' => [
    'enablePrettyUrl' => true,
    'showScriptName' => false,
],
```

**Comment by vicmonmena** [comment]
Ouuu yeah! The problem was 'urlManager' was not included inside 'components' ;) Thx so much!

By the way! Wich extension do you recommend me to create my Admin dashbiard that let me manage all my database tables?

**Comment by tvats1988** [comment]
In my case, I just changed 
`'showScriptName' => false `
to 
`'showScriptName' => true`

Now my App is working properly.
