### ISSUE TITLE
yi2-user + other entities

### ISSUE THREAD

**Issue by vicmonmena** [amnah/yii2-user#93]
Hi!

I'd like to know if I can manage all my model classes (database table) from /user/admin section with this extension

**Comment by amnah** [comment]
You can see the functionality using the [demo](http://yii2.amnahdev.com/user). 

Basically you can manage the users there, but you'll need to have to set up the others yourself. [Gii](http://www.yiiframework.com/doc-2.0/guide-tool-gii.html) would be very useful here.

**Comment by vicmonmena** [comment]
Thx! I've already seem how it works but I nees to know if I can create my admin dashboard based on this extension.

Anyway, thanks a lot for supporting
