### ISSUE TITLE
Registration via social network

### ISSUE THREAD

**Issue by rommcr** [amnah/yii2-user#96]
Will you implement this future?

**Comment by amnah** [comment]
Do you mean [this](https://github.com/amnah/yii2-user/blob/master/SOCIAL.md)?

**Comment by cicsolutions** [comment]
I’m curious about this feature too?

Many websites today allow users to register/start their new use account quickly by pulling data from social networks.  It seems with Amnah User that the social login only applies to users that already have user accounts.

Am I/we misunderstanding how Amnah User is set up, and how to utilize the social features?

Thanks so much for all you do!

Caleb

**Comment by amnah** [comment]
Guess I need to add some header links to the [docs](https://github.com/amnah/yii2-user/blob/master/SOCIAL.md#registrationlogin-using-social-auth) ...

**Comment by cicsolutions** [comment]
Sorry, I’m reading the docs better now.  I’ll follow the steps!

**Comment by rommcr** [comment]
Can you add this future to demo?
I don't see that in http://yii2.amnahdev.com/user/register

**Comment by amnah** [comment]
Done!

http://yii2.amnahdev.com/user/register
