### ISSUE TITLE
Social auth + login by the email from social network

### ISSUE THREAD

**Issue by rtwent** [amnah/yii2-user#97]
I have the possibilty for authorization by two ways: classical (email + password) and social (via facebook). So lets create situation:
1. Authorization by the username is forbidden (email only)
2. User register on the site via facebook. His email is stored in our database.
3. User logout.
4. User is idiot, second time he want to login by his email (he forget that he use facebook). He typing his email and some password.
5. User got the exception:"Hash is invalid" in 
~\yii2\advanced\vendor\yiisoft\yii2\base\Security.php line 581
<code>
if (!preg_match('/^\$2[axy]\$(\d\d)\$[\.\/0-9A-Za-z]{22}/', $hash, $matches) || $matches[1] < 4 || $matches[1] > 30) {
            throw new InvalidParamException('Hash is invalid.');
        }
</code>
Because our password field is not starting from $2 (it is empty).

**Comment by rtwent** [comment]
Could I ask You?
Can I use the value of api_key field as a part of key for reversible encryption of some user data?
Is it a constant? Or something could change it?

**Comment by amnah** [comment]
Not sure if this is the best way to handle it, but I added a login check. Eg, if the user registered via facebook, then it will redirect to facebook to login.

https://github.com/amnah/yii2-user/commit/623d60be69c9997329d98a3d8bee2b0e22ae4208

Seems like this is too dangerous though ... especially if they're not logged in, or if they're logged in as a different user. Hmm need to sleep on it. I'm most likely going to have to change it.

Regarding your question, ```api_key``` isn't really used out of the box. It's meant to be used if you create an api or something

**Comment by amnah** [comment]
I've decided to take the safe route: prevent the user from using the regular login when registered via social auth. This is how stackoverflow does it, and it makes sense to me.

https://github.com/amnah/yii2-user/commit/e511339180e3a2dbcc0700f3d5ac674e73900e90
