### ISSUE TITLE
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'amnah\yii2\user\m odels\Role' not found'

### ISSUE THREAD

**Issue by msstoci** [amnah/yii2-user#98]
Basic usage: composer <command>
For more information just type "composer".

C:\xampp\htdocs\basic\_protected>php yii migrate --migrationPath=@vendor/amnah/y
ii2-user/migrations
Error: Migration failed. Directory specified in migrationPath doesn't exist.

C:\xampp\htdocs\basic\_protected>php yii migrate --migrationPath=@vendor/amnah/y
ii2/user/migrations
Yii Migration Tool (based on Yii v2.0.4)

Total 1 new migration to be applied:
        m150214_044831_init_user

Apply the above migration? (yes|no) [no]:y
*** applying m150214_044831_init_user
    > create table {{%role}} ... done (time: 0.440s)
    > create table {{%user}} ... done (time: 0.436s)
    > create table {{%user_key}} ... done (time: 0.411s)
    > create table {{%profile}} ... done (time: 0.436s)
    > create table {{%user_auth}} ... done (time: 0.478s)
    > create unique index {{%user_email}} on {{%user}} (email) ... done (time: 0
.619s)
    > create unique index {{%user_username}} on {{%user}} (username) ... done (t
ime: 0.469s)
    > create unique index {{%user_key_key}} on {{%user_key}} (key_value) ... don
e (time: 0.493s)
    > create index {{%user_auth_provider_id}} on {{%user_auth}} (provider_id) ..
. done (time: 0.688s)
    > add foreign key {{%user_role_id}}: {{%user}} (role_id) references {{%role}
} (id) ... done (time: 2.026s)
    > add foreign key {{%profile_user_id}}: {{%profile}} (user_id) references {{
%user}} (id) ... done (time: 2.074s)
    > add foreign key {{%user_key_user_id}}: {{%user_key}} (user_id) references
{{%user}} (id) ... done (time: 2.048s)
    > add foreign key {{%user_auth_user_id}}: {{%user_auth}} (user_id) reference
s {{%user}} (id) ... done (time: 1.407s)
    > insert into {{%role}} ... done (time: 0.122s)
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'amnah\yii2\user\m
odels\Role' not found'

in C:\xampp\htdocs\basic\_protected\vendor\amnah\yii2\user\migrations\m150214_04
4831_init_user.php:93

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

C:\xampp\htdocs\basic\_protected>]
']' is not recognized as an internal or external command,
operable program or batch file.

C:\xampp\htdocs\basic\_protected>

**Comment by amnah** [comment]
hmmm ... how did you install the module?
